### ISSUE TITLE
[Close 예정]25th schedule plan

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#106]
# 2주간 총 56 시간

## 평일, 주말, 휴일 상관없이 매일 4시간씩, 횟수 상관 없음.

- 추가로 한번에 집중한 시간이 몇 시간인지에 대한 내용 추가

계획한 시간을 썼는지에 대한 체크이므로, 시간 체크를 잘 해주세요.

**Comment by ytw9699** [comment]
- [ ] 4/22일 4 시간
- [ ] 4/23일 4 시간
- [ ] 4/23일 4 시간
- [ ] 4/23일 4 시간
- [ ] 4/23일 4 시간
- [ ] 4/23일 4 시간

**Comment by ytw9699** [comment]
28,29일 2시간 부족
총 56시간 중 52시간완료
92퍼센트 완료
