### ISSUE TITLE
[ 추가 정리중 ] 현재까지의 유닛테스트의 고민점 및 코드리뷰

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#110]
## 1. 테스트 할 레벨?을 ControllerTests가 주가 되야할것같은 생각

BoardMapperTests, BoardServiceTests, BoardControllerTests 순으로 작성해왔는데
이렇게 작게 나누다보면 문제가 발생했을때 원인을 찾기 쉽다는 장점이 있으나,
단점으로는 비효율적이다 라는 생각이 들었다. 
그래서 요청이 들어가는 시점인 Controller에서부터 테스트를 하는게
전체적인면에서 효율적일것이라고 생각이 된다. 

## 2. 테스트 클래스와 메소드의 분배를 어떻게 해야할지

- 하나의 클래스에 여러 테스트 메소드를 둘것인지, 아니면 
- 하나의 클래스에 하나의 테스트 메소드만 둘것인지
- 하나의 클래스에 여러 테스트 메소드가 있게되면 복잡하고 문제가 발생했을때 찾기 어렵다는 단점
- 하지만 하나의 클래스에 여러 테스트가 있으면 작성과 실행하는데 효율적이다 라는 장점

## 3.  위 2번과 겹치는 문제인데 
하나의 클래스에서 게시글 crud 테스트를 통합해서 한번에 하고싶은데 그게 불가능한것 같다는 생각..
- 게시글 생성을 처음에 하고나서 , 테스트 클래스가 종료되지 않으면 DB에 커밋이 되지 않는것 같다..
- 그래서 조회를 하려고 하면 아직 DB에 값이 없다..
- 당연히 수정도 못하고, 삭제도 할수 없다.
- 결국 하나의 클래스에는 여러 테스트 메소드 작성을 하는것이 적절치 않은것인지?
- 아니면 다른 방법이 있는것인지 찾고 있다. 

-다른 방법을 찾았다.

- Junit은 테스트 코드의 실행 순서를 보장하지 않는다고 한다. 
- 4.12전에는 랜덤순이였다가. 4.12부터 정해진 실행 순서가 있다
- 메소드 이름의 해시코드로 순서를 정하는게 기본 디폴트다. 해시코드로 ordering함

- @FixMethodOrder(MethodSorters.NAME_ASCENDING)
- 해당 옵션을 지정해주고 메소드 이름을 맞춰주면 의도한대로 테스트 실행이 가능하다.
- 추가적으로 어노테이션이 필요
- 메소드의 이름 오름차순으로 정렬됨 이러한 순서로 실행되는것

- junit 5 부터는 
- TestMethodOrder - 테스트 실행 순서 지정 5.4버전부터 테스트의 순서를 지정할 수 있는  
- @TestMethodOrder 어노테이션이 제공
- 일반적으로 테스트는 순서에 의존하지 않도록 작성하는 것이 유지보수 측면에서 바람직
-  하지만 시퀀셜한 업무흐름을 순서대로 테스트하는 것이 테스트 코드 작성에 편할 경우에 사용하는 경우가 있다. 
- 이전 버전에서 제공되던 @FixMethodOrder 어노테이션은 메소드 이름에 의한 순서만 지정할 수 있었으므로 테스트 메소드 앞에 알파벳을 넣어서 순서를 지정하거나 하는 불편한 방법
- 새롭게 추가된 @TestMethodOrder 어노테이션은 알파벳 순서 이외에도 어노테이션으로 직접 순서를 지정하거나 랜덤한 순서로 실행하는 기능을 제공

- 결론적으로 db에서 값을 정상적으로 잘 가져온다. 하나의 테스트 클래스에 여러 테스트
메소드가 작성가능한것 
- 이제는 선택의 문제인것 같다. 하나의 클래스에 여러 테스트 메소드를 작성할것인지
- 아니면 하나의 클래스에 하나의 테스트 메소드만 작성할것인지

## 4.  유닛테스트 작성의 장점
유닛테스트를 작성하면서 로그를 보다보면 불필요한 로직들을 발견하고 리팩토링할 기회가 있다.

## 5. 현재의 도키프로젝트의 유닛테스트들은 서비스가 제공될때 테스트할수있는것이 아니다.
서비스를 멈춘 상태에서만 테스트 할 수 있는 로직이다.

## 6. 테스트의 범위의 설정에 대해
너무 많은 요청에 따른 테스트도 많아지는데 핵심적인 요청만 테스트할것인지, 전부다 할것인지 여부 결정 및 이제는 최소 우선순위를 세워서 테스트작성이 필요하다는 생각

**Comment by ytw9699** [comment]
코드리뷰 커밋 코드: 
https://github.com/ytw9699/Dokky/commit/e2b9a8ddcc926ac64f2b82a10484fa2a9ea37a8a

풀리퀘스트 할때 일부 커밋만 반영하는 방법을 아직 못찾아서 이렇게 일단 올려봅니다.

**Comment by jongfeel** [comment]
commit을 여러번 하지 말고 조금씩 한 다음에 pull request를 주는 방식으로 하시면 됩니다.

그리고 한꺼번에 많이 하지 마시고 하나씩 천천히 해보세요. 한번에 너무 많은 테스트 코드를 만들었습니다.

그리고 테스트 코드는 테스트가 통과 됐는지 안됐는지 여부를 체크하는 코드가 있어야 합니다. (assert)

이걸 조금만 짜고 pull request를 주는 건 어떨까요?

**Comment by ytw9699** [comment]
네 알겠습니다 조금만 짠다고 했었는데.. 하다보니 이게 또 길어졌네요ㅠㅠ

assert도 추가해보겠습니다!

**Comment by jongfeel** [comment]
5번에 대한 의견

- 서비스 환경과 동일한 local 환경을 구성하고 unit test 진행

**Comment by ytw9699** [comment]
리뷰후 : 멘토님 >
- pull request를 branch가 꼬이지 않게 조금씩 요청
- assert 구문은 꼭 정상적인 테스트 결과가 아닌 것도 가능 (null, "")
  - https://github.com/testdouble/contributing-tests/wiki/Arrange-Act-Assert
- 환경 구성에 대한 의견: https://github.com/ytw9699/Dokky/issues/110
- Unit test의 정확한 의미: 내가 만든 method의 동작을 확인하는 코드를 작성

**Comment by ytw9699** [comment]
Arrange, Act, Assert" is a testing pattern to describe the natural phases of most software tests.
3A : 

Arrange describes whatever setup is needed
Act describes the subject's behavior that's under test (and typically only describes a single line needed to invoke that behavior)
Assert describes the verification that the subject's behavior had the desired effect by evaluating its return value or measuring a side-effect (with a spy or mock)
