### ISSUE TITLE
Propose: Spring boot project reviewer

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#113]
제가 한이음 프로젝트 멘토로 활동하고 있는 건 아실건데요.

이번에 한팀이 spring boot로 프로젝트를 진행하고 있습니다.
그 프로젝트에 reviewer 정도로 참여해서 함께 해보는 건 어떨까 싶어서요.

이걸 제안드리는 이유는
- 남이 짠 코드를 리뷰해 보면서 코드 의도 파악하기
- 내가 모르는 부분, 훨씬 나은 코딩방법 배우기
- 그리고 내가 알려줄 수 있는 코딩 팁 및 기술 지식 전달
- 결국 peer review를 통해 서로 배우는 장점을 직접 실천하면서 진행

괜찮으시면 이 팀에게도 함께 해보자고 할 예정입니다.

repository는
https://github.com/kyu9341/TeamHash
입니다.

여기 프로젝트에 두 분은 작년 home coming day때 본 분입니다.
조승현님하고 권영언님이에요.

**Comment by ytw9699** [comment]
네 멘토님ㅎㅎ 모두 괜찮다고 하시면 저는 좋습니다. 
스프링부트도 접하고, 리뷰어도 해볼 수 있고 정말 좋은 경험이 될거같아요~!

**Comment by jongfeel** [comment]
네 알겠습니다.

만약 참여하시게 되면 조금 적극적으로 해주셨으면 좋겠습니다.

**Comment by ytw9699** [comment]
네 알겠습니다.
