### ISSUE TITLE
프로젝트 설계를 위한 준비 작업

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#121]
## 0. 설계

 	- 해결한 문제를 이해했으면 그 문제를 코드로 어떻게 해결 할지 설계해야 한다
 	- 코드의 구조적 청사진이라고 생각하면 쉽다
 	- 코딩에 뛰어들기 전에 일정 수준의 설계가 있어야 한다.
 	- 나는 어떻게 코딩을 해야하는지에 설계도가 없이 그때그때 상황에 맞춰 코딩을 해왔다.
	- 소프트웨어 개발의 중요한 축이라 할수 있는
	- 설계와, 테스트를 뛰어넘고 프로젝트를 진행해와서 큰 구멍이 있는것 같다.
 	- 요구사항 > 설계 > 테스트 > 코딩 > 
 
## 1. 설계가 필요한 이유

 	- 제품을 만들기 위해서는 설계도와 같은 밑그림이 필요
 	- 이것이 있어야 무엇을 만들 것인지 명확해지고,
 	- 이에 참여하는 사람들은 이를 공유하고 연구 및 개발할 수 있다.
 	- 설계가 후순위가 되면 시스템을 개발하는 비용이 더 많이 들고, 일부 또는 전체 시스템에 변경을 가하는 일이 현실적으로 불가능해진다(Clean Archictecture)
 	- 설계를 통해 우선순위와 모듈 트리가 나온다면 순서대로 딱 딱 진행, 엄청난 삽질들을 미연에 방지효과
 	- 코딩을 시작하는 단계에서 성공 가능성에 대한 확신을 얻음 
 	- 개발 시간도 예측 가능

## 3. 설계의 방향성

 	- 나만 이해할 수 있는것이 아닌 남도 쉽게 이해 할 수 있게  > 그러면 추후 쉬운 인수인계가 가능
 	
 	
## 4. 설계 리스트

 	- DB설계 Database(개념적 설계 ,논리적 설계 ,물리적 설계)
 	- Sequence Diagram
 	- USE CASE Diagram
 	
## 3. 설계를 위해 필요한 개념들 정리

![image](https://user-images.githubusercontent.com/35983608/81943158-fec55600-9635-11ea-909d-00618dbc3391.png)

### 3-1) 모델링

 	- 소프트웨어 개발에 있어 가장 우선적으로 해야 할 일은 고객의 문제를 해결하기 위해 문제를 이해하는것
 	- 바로 그것이 모델링과 관련
 	- 소프트웨어를 구성하는 모듈들을 식별하고 이들의 연결 관계를 그림으로 표현하는 것
	- 모델링의 결과물이 명확하면, 프로그래머들은 보다 쉽게 프로그램을 만드는 것이 가능.
	- 그로 인해 생산성 및 품질과 직결

### 3-2) UML(Unified Modeling Language)

 	- 분석과 설계단계에서 쓰이며 요구분석, 시스템설계, 시스템 구현 등의 시스템 개발 과정에서, 
 	- 개발자간의 의사소통이 원할하게 이루어지도록 표준화한 대표적인 객체지향 모델링 언어이다. 
 	- 모델링 언어란 우리가 만들고자 하는 것을 그래픽하게 표현할 수 있는 시각적 언어를 의미 
 	- UML의 장점은 분석 모델과 설계 모델을 표현하는 방식이 다르지 않다는 것이다. 즉 통일됨
 	- UML은 시스템의 구조와 동작을 표현하는 13개의 다이어그램을 제공해준다. 

### 3-3) 대표 다이어그램

 	- 유스케이스 다이어그램
 	- 클래스 다이어그램 
 	- 순차 다이어그램 
 	- 패키지 다이어그램
 	
### 3-4) 갑자기 보이는.. 어려운 개념들 (아키텍처 VS 설계) 
 	
 	 - 소프트웨어 아키텍처는 전체 시스템 설계에 관한 것이고 
 	 - 소프트웨어 설계는 개별 모듈/구성 요소/클래스 수준에 중점?...
 	 - 아키텍처는 구조,골격, 시스템의 가장 높은 수준의 추상화
 	 - 도키 프로젝트의 아키텍처? : 클라이언트 - JSP(뷰계층) - Spring MVC(프리젠테이션 계층) - 비즈니스 로직층 - Spring JDBC - DB(오라클)

**Comment by jongfeel** [comment]
아키텍쳐는 정의하기가 어려울 수 있는데
전체 시스템을 이해할 수 있는 시스템 다이어그램 + 간단한 정의 및 설명이라고 보시면 됩니다.

이건 책으로 공부해서 알기에는 어려움이 많고
다양한 소프트웨어 설계 및 개발 경험이 어느 정도 동반 되어야 조금은 가능해지는 영역입니다.
물론 소프트웨어의 기반 지식과 개념을 많이 이해하고 있는 상태여야 하겠죠.
특정 프로그래밍 언어 코딩 좀 할 줄 알고, 프레임워크+라이브러리 쓸줄 알고, 알고리즘 잘 짜는 것과는 많이 다른 영역이라고 보시면 됩니다.

**Comment by ytw9699** [comment]
멘토님 리뷰내용:
### 분석/설계의 중요성

- 이론적인 지식을 습득하기에는 어려움이 많은건 사실
- 실제 적용을 해보는 경험을 많이 해야 하고, 내가 설명할 수 있는 이유가 들어있는 문서를 만들어 내는게 중요
- 다음 프로젝트를 진행하시게 되면, 충분한 시간을 가지고 적용해 보는 시간을 가져보기를 권장합니다.
- 그래서 분석/설계 문서가 나오고 구현 단계에 들어갔을 때 그럼에도 불구하고 **문제점이 발생하면 분석/설계 문서를 업데이트**해서 코딩한 구현의 결과물과 일치하도록 만들어야 함
- 설계를 잘못해서 이런 일이 발생했구나(X)
- 설계할 당시에 생각지 못한 걸 찾아냈고 보완한다(O)
