### ISSUE TITLE
요구사항과 관련된 모든것

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#124]
요구사항 명세서(Software Requirements Specification)

는 요구사항을 분석하여 명확하고 완전하게 기록하는것이다. 즉 스펙에 대한 사항을 명세

소프트웨어 시스템이 수행해야 할 모든 기능과 구현상의 제약 조건에 대해 

개발자와 관련자(클라이언트, 기획자, 경영진 등)가 합의한 스펙에 대한 사항을 명세

서비스를 구현하기 위해 요구사항을 명확하게 정리해야 할 필요가 있다.

## 1. 기능적, 비기능적 요구 사항 명세서(SRS, Software Requirements Specification))

 	- 요구사항 분석 단계에서 나오는 최종 산출물이 바로 요구사항 명세서
 	
 	- 기능명세란 사용자의 관점에서 최종 제품이 어떤 모습이며 어떻게 동작할 것인지를 기술한 문서
 	- 프로젝트의 최종 산출물이 어떤 모습이며 어떤 일을 수행하는지를 자세히 기술
 	- 무엇을 만들 것인지를 분명히 하는 문서
 	- 최종 사용자의 입장에서 기술한 문서기 때문에 내부 구현 또는 설계 이슈는 포함되지 않는다.
 	- 기능 요구사항은 목표 시스템이 반드시 수행할 수 있어야 하는 기능(동작)에 대해 기술하는 것으로 요구사항 정의에서 가장 중요한 영역이며, 	도출된 요구사항은 기능점수로 산출 될 수 있어야 한다. 
 	- 기능명세서는 구현해야하는 기능에 대해 상세하게 설명하는 문서. 해당 기능이 어떻게 작동해야하고, 작동이 되지 않았을 때는 어떻게 처리(에러)해줘야하는지에 대한 상태를 기재
	
https://github.com/ytw9699/Dokky/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%AA%85%EC%84%B8%EC%84%9C

## 2. 요구사항 명세서의 중요성
 	
 	- SRS가 중요한것은 스펙을 정함으로써 모든 개발의 모든 분야 일정 예측, 설계 구현, 테스트의 기준이 되고
 	- 개발 진행 상황파악, 의사소통이 가능해짐 
 	
## 3. 요구 사항 변경 관리

https://github.com/ytw9699/Dokky/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B3%80%EA%B2%BD-%EA%B4%80%EB%A6%AC
 	
## 4. 요구 사항의 핵심

 	- 요구사항은 소프트웨어 개발에 필요한 중요한 요소 중 하나이며,

 	- 궁극적으로 개발할 소프트웨어 시스템이 하는 일과 할 수 있는 일이 잘 들어가도록 내용을 적도록

## 5. 좋은 요구사항 명세서가 가지고 있는 특징

 	- 요구사항 명세서를 읽는 작업자(개발자, 디자이너 등)가 이해하기 쉬워야 한다.
 	- 무엇이 구현되어야 하는지 명확하게 작성한다.
 	- 하나의 요구사항에 여러가지(복수) 요구사항을 작성하지 않는다.
 	- 애매한 단어를 사용하지 않고 명확하게 기재한다. ( ~ 있으면 좋겠다 → ~ 기능 필요)
 	- 동일한 용어를 사용한다. 댓글, 코멘트, 덧글과 같이 모두 같은 의미를 다르게 표현하지 말라는 의미

**Comment by jongfeel** [comment]
왠지 애자일에서 쓰는 용어인 **사용자 스토리** 와 같은 느낌이 나는군요.

어떤 문서를 참고해서 작성하셨는지 모르겠지만

https://brunch.co.kr/@insuk/14

이 부분을 보시면 스토리라고 얘기하는 내용이 요구사항이라고 쓰신 내용이 거의 일치한다고 볼 수 있습니다.

**Comment by ytw9699** [comment]
멘토님 리뷰내용
- 요구사항의 범위가 넓은데, 여기 적은건 기능적 요구사항만 적어주셨네요
- 주로 성능과 관련된 비기능적 요구사항도 있을 수 있습니다. 복잡하게 따지고 들어가면 타 플랫폼 이식성이라던지, 윤리적 요구, 사생활 보호 등 다양합니다.
- 중요한건 요구사항은 소프트웨어 개발에 필요한 중요한 요소 중 하나이며, 궁극적으로 개발할 소프트웨어 시스템이 하는 일과 할 수 있는 일이 잘 들어가도록 내용을 적는게 중요합니다.

**Comment by ytw9699** [comment]
요구사항은 2가지 참고 + 제 생각대로 작성했어요 
블로그 : https://m.blog.naver.com/ndb796/220635189639
책 : 코드로 배우는 스프링 웹프로젝트

스토리라고 하는게 이해가 안가.. 처음 애자일 첫 포스팅부터 봤더니 이해가 되네요ㅎㅎ

겸사겸사 폭포수와 애자일도 정리해봤습니다.   https://cg-developer.tistory.com/450

애자일이 체계적인 개발 방식인것 같다는 생각이 드네요

이번에 정리하면서 알게 된것이 애자일에서 쓰이는 사용자 스토리는 사용자의 관점에서만 작성이 되어야 하고 

소프트웨어 개발자들이 사용하는 용어들이 들어가서는 안된다것이였네요.

**Comment by ytw9699** [comment]
위키의 홈화면 구조 변경
앞으로 설계 리스트 핵심 사항을 위키 홈에서 쉽게 보여주는것으로 정리
https://github.com/ytw9699/Dokky/wiki

**Comment by ytw9699** [comment]
기능적 요구사항 명세서 작성시의 고민사항

화면에 보여지는것만으로도 이것을 기능이라고 봐야하나? 기능에 대한 혼동..?
기능과 화면에서 보여지는것에 대한 혼동? 어떤 특정한 동작을 하는것을 기능으로 볼것인가?
기능적 요구사항에 들어갈만한것인지의 구분과 기준을 가져야함

예를들어..아래와 같은것들에 대해

- 메인 화면에서는 실시간게시글, 한달간인기글, 한달간기부글 리스트를 볼 수 있다.*
- 게시판 리스트는 전체글보기,공지사항,자유게시판,묻고답하기,칼럼/Tech, 정기모임/스터디 카테고리로 나뉜다.*
- 모든 게시판 리스트에는 조회수, 좋아요수, 기부금액, 작성시간을, 작성자닉네임을 볼 수 있다.*
-  어떤 화면에서도 왼쪽의 메뉴탭을 볼 수 있다.*
- 나의 댓글 리스트에서는 총 댓글수를 보여줘야 한다.*
- 나의 스크랩 리스트에서는 총 스크랩수를 보여줘야 한다.*

어떠한 하나의 동작이 이루어지는것만을 기능으로 볼것인가
아니면 화면에서 보여지는것들에 대한 것도 기능으로 볼것인가

나름의 방향성이 필요

**Comment by ytw9699** [comment]
요구사항 명세서를 작성하면서 느끼고있는것 :

- 가장 맨처음에 이 작업을 잘했다면 하는 아쉬움 다음번에는 무조건 요구사항부터 제대로 할것

- 요구사항 작업전에, 프로젝트를 부분부분적으로 보고있어 좁은시야를 가지고 있었다면, 후에는 전적으로 바라보게됨

- 전체적으로 바라보다보니 시야가 넓어지고, 평소에 들지않던 생각도 들게됨 예를들어 신고관리같은경우 한 종류의 게시판으로 만들었다면 더 좋았을것 같다는 생각이 들게됨, 현재는 매우기능이 작고 불편한 구조

- 요구사항을 작업하다보니 꼼꼼한 체크가 가능해서 못보았던 결함들을 발견하게됨

**Comment by jongfeel** [comment]
### 기능에 대한 구분

- 데이터를 어떻게 처리해서 결과를 내는가에 대한 기준
- 화면 위주의 기능 설명이 많고 그 흐름대로 가면 => GUI가 주가 되는 시스템으로 설계
- 기능이 동작하고 기능의 결과가 나와야 하는 흐름이라면 => API 호출 결과나 콘솔 프로그램으로 설계

**Comment by ytw9699** [comment]
멘토님 이전 리뷰:

요구사항 문서 쓰기

나열식 보다는 구조화된 형태 (트리, 그래프-마인드맵)
설계 할 때, 화면 설계를 사용해서 더 구체화 시킴

요구사항을 반영하면서, 스냅샷 화면의 특정 구현 부분이나 제약사항들을 추가해서 덧붙임
