### ISSUE TITLE
요구사항 작업으로 인해 발견한 결함 todo리스트

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#129]
요구사항을 검토하다보니 평소 몰랐던 결함들을 발견할 수 있었음

- [x] 모든 쓰기 제한이 걸린 회원이 글쓰기를 눌렀을때 접근제한페이지를 보여주는것보다는, 쓰기 기능이 제한되었음을 나타내는 경고창을 보여주자
- [x] 모든 쓰기 제한을 했을때, 댓글이 써지는 현상을 못쓰게 고쳐야함
- [x] 모든 쓰기 제한시, 로그아웃 버튼이 사라져버리는 현상 고치기
- [x] 관리자 권한 페이지에서 사용자를 회원 이라는 이름으로 변경하기
- [x] 특정 게시글과 댓글을 신고해도 아무한테도 알림이 가지 않도록 하기
- [x] 로그인 하지 않은 상태에서는 댓글의 신고버튼이 보이지 않게 하기
- [x] 특정 관리자가 모든 쓰기 제한을 걸면 특정 관리자의 닉네임으로 사용자에게 알람이 가야함
- [x] 사용자는 쓰기 제한이 되었다는 알림을 클릭하면 내 정보 페이지로 가야하고, 내정보에서 계정의상태 확인을 할수 있어야 한다
- [x] 사용자의 계정이 복구되면 사용자에게 알림이 가야한다
- [x] 환전,충전요청이 승인되면 특정 관리자의 닉네임으로 사용자에게 알림이 가도록 변경
- [x] 댓글내용을 비우고 작성시 경고창 띄우기

**Comment by jongfeel** [comment]
요구사항 문서 쓰기
- 나열식 보다는 구조화된 형태 (트리, 그래프-마인드맵)
