### ISSUE TITLE
위키의 파일을 변경이력 포함하여 이동하는 방법은 없을까요?

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#138]
현재 위키에 있는 리뷰파일들을 rivision 기록들을 살려서

아래 주소 code안으로 옮기려하고 있습니다.

https://github.com/ytw9699/Dokky/tree/master/dokky/document/review_Of_mentee

문제는 파일 복사를 해버리면 변경된 기록들이 모두 사라져버리게 되버리네요..

document 폴더 한곳에 프로젝트 관련 모든 문서들을 모아 두고 보기 쉽게 하고 싶은데

변경된 이력들을 포기해야할지요..

현재 깃허브에서는 wiki탭에서만 리뷰파일이 확인가능하고

깃허브 code에서는 볼수가없습니다. taewon_wiki가 클릭이 안되는 현상
https://github.com/ytw9699/Dokky/tree/master/dokky/meeting
![image](https://user-images.githubusercontent.com/35983608/83656070-102ccd00-a5fa-11ea-9809-f1ac30bb0f46.png)

하지만 이클립스에서는 또 보이는 상태입니다..

![image](https://user-images.githubusercontent.com/35983608/83656105-1cb12580-a5fa-11ea-87b6-6f59f2d5b89a.png)

물론 어렵지만 위키에서 삭제한다해도 확인하는 방법은

https://github.com/ytw9699/Dokky.wiki.git

위키 자체를 현재 브랜치로 떠두었기에, 소스트리에서 확인을 하는 방법은 있습니다만,

찾아서 들어가야하는 수고로움은 있네요

![image](https://user-images.githubusercontent.com/35983608/83657412-c9d86d80-a5fb-11ea-9552-cf5adb1bca28.png)

변경이력 볼 일이 거의 없을 거 같아서 크게 상관은 없겠습니다만

혹시 라도 방법이 있다면 살리고 싶긴하네요.

**Comment by jongfeel** [comment]
이건 git submodule를 찾아보시면 됩니다.
github 상에서는 클릭(?)이 안되고
각각 repository가 존재하기 때문에 local 상에서는 문제 없습니다.

많이 불편하시면 README.md에 그냥 wiki의 page를 따로 링크 걸어주는게 좋습니다.

**Comment by ytw9699** [comment]
오 감사합니다~~!
