### ISSUE TITLE
유스케이스 3.0 > 4.0

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#179]
유스케이스 3.0버전으로 업데이트

게시글과 댓글에 향하고 있던 유스케이스들을 단순화 시키기 위해 일단 제거하였습니다.

그런데 단순화 시키고보니 유스케이스 다이어그램에서 관계설정이 헷갈립니다.

- 게시글과 사용자 로그인

- 댓글과 사용자 로그인을

연간관계로 표현해야할지, (유스케이스와 액터간의 상호작용이 있음을 표현한다. 유스케이스와 액터를 실선으로 연결한다)

포함관계로 표현해야할지, (필수적 관계로서 하나의 usecase가 실행되기 위해 반드시  다른 usecase가 실행되야 하는 관계)

아니면 표현 자체를 안해야할지, ( 단순화를 위한 어쩔수 없는 감수 )

일단 포함관계로 표현을 하고 include 를 표기 하였습니다. 

왜냐하면 글과 댓글 기능을 사용 하기 위해서는 반드시 로그인이 필요한 부분들이 있습니다.

예를들어, 쓰기,수정,삭제등, 하지만

반대로 글과 댓글을 읽기, 상세보기등은 로그인이 필요하지 않습니다.

지금 이렇게 애매한 상황이 된것은 복잡하면 안되고 단순해야하다보니 나타난것인데 그렇다면

저러한 포함관계 표현도 정확하게 나타내지 않고 표현 자체를 안하는게 맞을지 고민입니다.

[Use Case Diagram 다이어그램 상세 보러가기 버전 3.0](https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7V3bkps4EP0aHjOFLoD06Msku1vJVqqSrU2etrDN2Gyw8WKc8eTrVwIJjCTb2AMYJ87LIBkJ0ed0q9VqEQuNlrt3ib9efIhnQWRBe7az0NiCEBKM2R9e85LXAAzdvGaehDNRV1Z8Cn8EotIWtdtwFmwqN6ZxHKXhulo5jVerYJpW6vwkiZ%2Brtz3FUfWpa38eaBWfpn4kax%2Bcsv7vcJYuRD1wafnDb0E4X4iHE%2FmGE3%2F6bZ7E25V44ipeBfkvS192I95ys%2FBn8fNeFXq00CiJ4zS%2FWu5GQcQlK2Um26UvcqAWGi7SZcQKgF1mP7890BjUaczeKwlW6f7jDvX3%2BdvufeCO1ng8%2FOf5s71co5n%2FhuS9fPejrXzI48gi0BqM%2BAUdWAOaXTxaVH8bJpA1v9wuo8E0jRM2qu9BkoYMmPf%2BJIg%2BxpswDeMVu2USp2m8ZDdE%2FIdhIfRRHPF2rDf0lP3b62MQhXPeNo3X1VePt2kUroJRwSabVT7Fq1QwE3hG%2BQiJ8u6D3V6VkNe7IF4GafLCbik0Q7yz1Aspg%2BeSYo6oWuyRCyBR6Qtez4uuS4DYhcDoDLwcpIEQzJgqiGKcpIt4Hq%2F86LGsHWaCDmZCTuU972Mu2Eyi%2FwZp%2BiKk52%2FT%2BBTVJDnjbTINjoxXGgg%2ByKMST4LIT8PvVS03iU80%2FRiHbCwFUsh2KkghV0Eg9ZN5kIpWCgjFMC7HRb6nokh0bA2ZIg2toW1RYj0OrCG2GKlYzcCVOparlhsx0Q4nCbuap4XMf2Fl80hNZXNaUzb3xpQNXkfZKOlY2aB51hpYhOnY2CK51t2V7YyZrdCik9pGW9I2gMyouhbJoCOORVnPrr%2FkMltNNutMFDm%2BgP%2FGEfesIZGWl%2FABMT4wLybvgg45%2Bvw2OyNGxgfWL8yvPV7PeiNvLUpFJRlmPWfsGuCMXfk4FMI8L8I0%2BLT2MwV9Zm52FVd%2Fs87xfAp33DhomGZl0R1oAuDCNxcIY%2BJoAANiQljV5uYQxhrCf22Ys22P%2FOzPOPTnib%2FUZMtemSvpJk3ib4FUq8xPZ3ILo0ip2hP7npQh1qSs6%2BMynM0yK%2B6LiilDIEia0TmHVhFBusYBBxgQwW0B4l1lgmMSTF6%2B8PZs1SaKX0V3WWG8q5ReitJswNeKJdKs5m3IXzn7%2FRUTp5BDPm%2FVsFHNzbCvUyjXYDLr2DsV9ChiK3Uu0RNmrIWZyLWVmcgzqAU2aIXXmlZ4V9YK2Be18G5ULTyzJ3EoqnHcheiRrgACqp63Bw3KQk2TemtzCDCHkKiT2aDM9RbOOJHuFRN%2Fv20QNjjD3dogQI1SHTAxjrMLLzPoNyVV5%2BqWXWrLvlTVBQUXJeQrRy5lm%2FOYh28Qr4G2YVHZZ4m7hhBKxxIHusS5DGHG2lzCo9sTLLWvLVggLUS3XsrM3yyy9iBbkPlJqvgeWd2e97HnnUyiePqt4p68LtwFYU33BIFeuSdy3KpO5IGOMTc5t6gTAFzf2phCSJm1ESGkPJgz5kXDdlafpIlMFsYUkKOtCdOwuBSBU%2F7%2BFdG5%2F21j%2BcObTSaZAbsBkPWu%2FLEMtorwa1HB51yGCBIODSkitGzgE7UZq8uffyB0exGKTkMOuq16kliHEdomBx22hqNhNdQMjgbV0vFrB6umw6UacKboXNfAmVZWWnTn5uYJYlqzdjtNmBdXjMKDXJiIX9ycYOnV519k8va1jTmjYG8xGoM0DwgYEOg4HGMbggDtrwsaWQpUFhfBLky%2F7F1nodB8w4CVylgoL5ShUPPOQhFfPRBCPUiG02sQYUpOh0jFLNz23jxwcZWULnSqfeTvpG3O6z0V8RppuGvm1DCQ%2FZe929b8hs2RIRMpHKlHtghzHhya2kIOrdScfBAN5%2FgYlgz93S5rUSUfbJtW1BK5JxSTFT4GScgg4Lupr1W62vsS11I6hOopXVPUlJpZ8fFVqmr7REaSVShWMu5cy3kaG7cmNicSUmTda3OalM15qBq7umZT7Qh0nInompbt%2FaYCrLt92A0VsLoUVP3lulRwlRQcCJxuqWBa%2BfebCnI3sSdU0KyCmhtVlwpa7o%2FbMRUMsYS%2BU4H2igqaVVADr5daBUzrUeFctxor7juGHfjIriG00nOeyXBUT3iGSEMmR%2BWZW3P2OZtnSOGZ1wHPvNtzeGG%2FpzbiXRgnOBjf7Whq8wxBx75Toe6G9JWoQJqiQsdejgdvjwr98nJUKhSJLq%2BlAlVPabVNBadvVOgJwqofC2BTEIOu17f0PHWfRv5mE04VmEVM8439YGcbQ3t7DVSWuwxq9oQmwMZMIjbysIv46hWjCtbIxg%2FI9RzkQPYzQOgyCnnYe8CXndw9102lUH9UFysiashJOpekr2BVv6KswHaZXtnQgQ4CLsWwgofj8bMPALrQdQj2lN7rc0oJtajhu7MJ1fxhcWNqVZ6HLPJm9kvhahpt%2Bfc1ZO28co85tUYcmqvs0dY7P6edfTt4Ss60517d72o9b6fwK5QoRzVvRyd0a1k7wHQg4g7uZeC6ykFzwwmCbsE9doLgDu5Z4AJ1owwYcyXbQTeIPod%2FfP0w3U5%2BzP6Mfw%2B%2FjP4OmerqM%2FNNps6UGQMeIdXlC2UewanzhKxk9msVL%2BLCuL5n5sUrXQt12tcWnLXzXqh32dL17LwXzbw5zfqjZpIb3M%2FbJvk%2Bwetlet0Sj4mDH2Qey%2FkpXO7pzppiM7ah%2Bqzjg9Ma4C7of5UPaDVP%2F7pEbp2fHrQf7AuX%2F4Aoe1REjUU1RU6EtFEfH5naQI6sXXLin4OcB2Knt2%2BbFVK4MkfhfMPsnOipMeJTaHzQYeIrDbxOrPLPkrS%2B9xEPCquet43JCQX4STxvfGlmDFCzpJyaH5Y7VyuImrJAj88G6v1yXIfnNe9og5aU6B5VtIrYhBaIqOUbyQbFd1WkETR8EKTb0ITxEOcd2wawJYZDW51ia%2FpGxh3by7B1qtuU9OrYwju2TWGrLjwNX0joFturfCeu%2BS%2BwVMLFv4jPCtTPozr2pcckqRJj80A9p7Upt8%2F0mYC7ibnMxChQYlf%2FZm63JsaUTn%2FH9iJsadU1KELjzWPLiuV%2FCpKrefn%2FrqDH%2FwE%3D)

**Comment by jongfeel** [comment]
로그인에 대한 include는 인증이 된 사용자의 상태를 뜻하므로 맞다고 봅니다.
정작 사용자가 로그인 usecase가 없는게 더 이상하네요.

어떤 기능의 use case가 로그인이 됐냐 안됐냐로 할 수 있다 없다로 보고 싶은건 맞지만
그럴꺼면 actor를 login actor로 바꾸면 훨씬 더 case 만들기가 쉽지 않을까 싶네요.

use case를 한개로 그리려고 하다 보니 복잡도가 생기는데
제가 예전에도 말씀드렸듯이 case를 분리해 여러개의 그림으로 그리는 게 더 명확할 수 있습니다.

actor - (로그인)
이 그림 한장

login actor - (글쓰기)
이 그림 한장

이렇게요.

**Comment by ytw9699** [comment]
아.. 액터를 2개로 나누는건 까진 생각을 못했네요.. 감사합니다!

**Comment by ytw9699** [comment]
[Use Case Diagram 다이어그램 상세 보러가기 버전 4.0](https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7V3fl6I4Fv5reGwP%2BQEkj6jVszunZ6fPds%2BZnqc5qJSyhWIjVlnz128CCUqIigiI3dZLQYAQ7vfdm5ub5Gqg0XL3S%2BytF79FMz80oDnbGWhsQAgJxuwfL3nPSgCGdlYyj4OZKNsXfAn%2B8UWhKUq3wczfFG5MoihMgnWxcBqtVv40KZR5cRy9FW97jsLiW9fe3C8VfJl6oSwdWPvyP4NZshDlwKb7C%2F%2Fyg%2FlCvJzIL5x405d5HG1X4o2raOVnV5aerEZ85WbhzaK3gyL0ZKBRHEVJdrTcjfyQS1bKTD6XvMuGGmi4SJYhOwHsML388cjDoMrD7Ltif5Ucvu5YfV9fdp98e7TG4%2BHfb1%2FN5RrNvA8kq%2BXVC7fyJU8jg0DDHfED6houTQ%2BeDFr%2BGiaQNT%2FcLkN3mkQxa9WrHycBA%2BaTN%2FHDz9EmSIJoxW6ZREkSLdkNIb8wzIU%2BikL%2BHKsNPad%2FB3W4YTDnzybRuvjp0TYJg5U%2FytlkssLnaJUIZgJHKx8hUV69vzsoEvL6xY%2BWfhK%2Fs1tyzRDfLPVCyuBtTzFLFC0OyAWQKPQEr%2Bd51XuA2IHA6AK8LFQCwZ8xVRCnUZwsonm08sKnfekwFbQ%2FE3La3%2FMp4oJNJfo%2FP0nehfS8bRKdo5okZ7SNp%2F6J9koDwRt5UuKxH3pJ8FrUcp34xKOfo4C1JUcKmVYBKWQrCCRePPcT8ZQCQt6M%2BrjI71QUiY6NIVOkoTE0DUqMJ9cYYoORipW4ttSxTLXskIl2OInZ0TzJZf4TK5tDKiqb1Zqy2XembPA2ykZJx8oG9b2WaxCmY2ODZFr3ULYLerZci85qG21J2wDSo2obJIWOWAZlNdvekstsNdmsU1Fk%2BAJ%2BjSPuGEMiLS%2FhDWJ8YF5MVgUdcvT5bWZKjJQPrF6YHTu8nNVGPhqUikIyTGtO2eXilF1ZOxTCvC2CxP%2By9lIFfWNudhFXb7PO8HwOdtw4lDBNz0V1oAmAc99cIIyJVQIYEB3CqjY3hzAuIfzHhjnb5shL%2F40Dbx57y5Js2SdzJd0kcfTiS7VK%2FXQmtyAMlaIDsR9IGeKSlMv6uAxms9SKe6JgyhDw42Z0zqJFRFBZ44AFNIjgtgBxbtLBMQnG79%2F482zUJk7%2FEtWlJ%2BNd4ew9P5u5fKy4R5qVfAz4J6fXr%2Bg4hRyyfquCjWquh71OoWyNyaxi71TQw5CN1LlEz5ixFnoi21R6IkejFlijFU5rWuHcWCtgX9TCuVO1cPSexLGoxmkXoke6Aggoet4O1CgL1XXqrfUhQB9ColZqg1LXWzjjRLpXTPz9tkFY4wx3a4MA1UrVZWIcpwdOatDvSqrWzS271JZDqaoDCi5KyEeOXMom5zEP3yBeAk3NoLLPErc1IZSOJQ7KEucyhClrMwmP7k%2Bw1Ly1YIG0EN16KTNvs0ifB%2BmAzIsTxfdIyw68jwPvZBJG05eCe3JduAvCiu4JAr1yT2S7VZ3IAh1jbnLuUScAuL210YWQUmsjQkhZMGfMTzXTWX2SJtJZGF1AjrYmTM3gUgRO%2BfcXRGd%2F30bywodNKhmX3QDIere%2FuA%2B2ivBrXsD7XIYIEg4NySO0rOET9TFWlr3%2FSOi2FopWQw66qXqSuAwjNHUOOmwNR81oqBkcNapVxq8drJoOl5aA00XnugZON7IqRXfurp8gujFrt92EfnDFKOxmwkT84O4ES2%2Fe%2FyKdt1%2BamNMK9h6jMajkAQENAh2HY0xNEKD9cUEjQ4HC4MLfBcm3g%2BM0FJpNGLCzfSyUn%2BxDofqZhTy%2BeiSEepQM58cgwpScD5GKXrjtuXlg4yIpbWgV68i%2BqTQ5X64pj9dIw11xTQ0D2Xs%2FuG3Nb9icaDKRwpF6ZIow59GmqU%2FIpu01J2tEw2t8NEOG%2Fk6XtaiSA9OkBbVE9hnFZCef%2FThgEPDZ1GuVrvK8xK2UDqFqStcUNaVmFnx8laqleSItyQoU2zPuUst5Hhu7IjZnFqTIsmvXNCmT81A1dlXNploR6Hgloq0btvebCrDq9GE3VMDqUFD1l6tSwVaW4EBgdUsF3ci%2F31SQs4k9oULJKqhro6pSobT2x%2B6YCppYQt%2BpQHtFhZJVUAOvda0CptWocKlbjRX3HcMOfGRbE1rpOc9kOKonPEOkIZOj8syu2PtczDOk8MzpgGfO%2FTm8sN9dG3FqxgmOxnc76tocTdCx71SoOiF9IyqQpqjQsZfjwPujQr%2B8HJUK%2BUKXa6lA1V1abVPB6hsVeoKw6seC0vaCuhCDrse39DJ1n4beZhNMFZhFTPODOTDTiaGDuQYqz7sMavaEJsDETCImcrCN%2BOgVowLWyMQDZDsWsiC7DBCqRyEHOwNcb%2BfupW4qheVXdTEiopo1SZeS9ApW9SvKCkyb6ZUJLWghYFMMC3hYDt%2F7AKANbYtgR6m9OqeUUIsavruYUM1vFtcurcrWIYt1M4dnwWoabnl%2BDVk6L9yjX1ojNs0V5mir7Z8r7X07uktON%2BdenO9qfd1O7lcoUY7iup0yoVtbtQN0GyIe4NYD11Y2mmt2EHQL7qkdBA9wLwIXqBNlQLtWsh10%2FfBr8Otfv023k39m%2F4n%2BHXwb%2FRkw1S33zHe5dGa%2FYsAhpDh8ocwjOLefkJ1V9mt7MwevdvulAWfldS%2FUqTd0vXjdS8m8Wc36o3qSa9zP%2Byb5IcFrr%2FTqLY%2BJhQfy3Zcv4bLPV9YUm7EJ1XedblzpAdwF%2FW%2BSQKt5%2Bh8lctf8dKA5MGsO%2FwFR5qiIGm5sipwIlVp9umXqA7Jl7ZIT%2FxjkPBI7vX%2FbrJDClmsULjfM1pmaGiM%2BhdoXHSe%2B8oDTiVX%2BURatHyTxoLDoeZuYnFGAH8TzxnVXxgB1lZRVMbHcpVpB1CUL9HRvoN4v23W8X3NOPtCSEj2iikZDsYk8r4o0gpqEIN2GJrSbOB%2FYNoAt0Wza6hRbXY6MB7b1sLWK05T05tjCB7ZNYasOPDUZErrF9iZ54prPwFIIF%2F8kPitQ06NaZt1tklSJsTmgmtPalNunSxPwMDH1TIwCJbbLOXO7NTG65fQPbGthS4uuQR4a7wDbl%2Bffw8nse%2FT6x9T776%2F%2BJPr%2B%2BvuHdpYtV5sAUcxrPVuNerVSFcDaE35I8SwAamnGD6tZ12HDcQEt0XQu6CVEy8yB%2FFUdxWMwHVp0GRwb13cZGuFl5kPcjJdK6AfVXUFdnhxRf1WmIVZaarCjmEyh3DCgJoZAHbBY2xNelMWKsalaNrI0e60L0ow1WKRXZb2Hi0UeGq60WZYa13BJehVUSF1jiuR%2BWW5RfpCn%2ByMigyvNkozqGpBVC4vpvEWC0rQSntJ4yJMYESIOXDy4JpFaPxyDIx29xjQc7fsVfmtWCFq6nr%2BRzF76rr%2B53WsDq7jCBwxM8HMbYHWDA1XHY1UNMFRzwvHVy61YYDUkmSeSOt432OoT181Ps9P979hlt%2B9%2FKhA9%2FR8%3D)

유스케이스 4.0을 다시 한번 만들어봤습니다. 

천천히 계속 생각해보니까 로그인 유스케이스를 2개씩이나 만들자니

혼란.. 복잡해 보이고..그래서 하나만 만들고

일단 위에서처럼 연간관계를 실선으로 표시해봤습니다.

이렇게 하면 유스케이스 하나로도 충분히 표현이 되지 않을까 싶어서요~

**Comment by ytw9699** [comment]
유스케이스 분리 

로그인 하지 않은 가정의 액터 

[Use Case Diagram 다이어그램 상세 보러가기 버전 4.0](https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7Vldc%2BI2FP01egxjS%2F58tA3dTiedzTS70%2FapI7ACboxFjAjQX98rWcKfBBJgu502L5GOpCvrnHuvrwwiyXL3qaSrxc88ZTnCVrpDZIwwxoHjwD%2BJ7CvEdrFG5mWWaqwGHrO%2FmAYtjW6ylK1bEwXnuchWbXDGi4LNRAujZcm37WlPPG%2FvuqJz1gMeZzQ36Mit8V%2BzVCw0bnthPfAjy%2BYLvXmAvWpgSmfP85JvCr1jwQtWjSypMaNPuV7QlG8bEJkgkpSci6q13CUsl8wazsw6sTcPiki8EMscOjY01fAPRxbb5yyGc5WsEM3tjtn78ry7Z16ycsbxH9sv1nJFUnoXVFZeab4xm0wSFGAUJbIRRigKVWOCwv5pgJCVbG6WeTQTvISnemWlyECYezpl%2BQNfZyLjBUyZciH4EibkciA%2BkJ7wXK4Da%2BRJ%2FTVsRHk2l2sFX7WPzjcizwqWHLzJAvCJF0J7pu0P8qMZlebZrgFpvj4xvmSi3MOUQ2ToM5u4MBxsaxdzNbRoOJdNNEi1X88PpmuBoKE1eodeLumJwFIIBd3lpVjwOS9oPqnRWBHNUs1TPeeeS2IVo38yIfaaPboR%2FJSrGefkm3LG3nhekyDkQ77JeMlyKrLXdpQP0aeXPvAMnuWgFLHcllLE6yggaDlnQq%2FqiHB4jI%2FrYs7ZCaRwjGIIpBjFFgoDNIlQ7CBwKkAiz8RYFVpeDtTG0xJac3Hg%2FD8cbH5wZrC5Nws2718WbPifCbYw%2BMbBhoffWhEKIMbGKKii7v9ge8eb7RBFJ6MtvFG02U5P1a9rKMWshKp%2F44zOS7rsSQUnlhKuRcmfmSFdVXHAXJbnHahBdoNXqHd1Xxu2B9RaZmmqYpxqYAYCsPI6irhhWxHS18N27QFFnFulP0wGwgyCCqNAxVIQozBR8ZYMFYewA5T%2Fkq7tIhPscUVV8trCFeSoDNdyb8%2FqkjnE5gCZ4c3I9Ppk6jQkz9%2BiznvZcDNwt1bMRDDBDla7erBOXTqZHQDId1IRosQKZAbUU%2BDBp91lgFX7H0mEH1LRvY6KttWR0XH6MmJrKEvhm%2Bno30rHgdDq63cbrdqJ7wbCDWWzbyycNxSAXQKLNJJfIwbfFkBHuf9Nv5JV53fZGbmmO941B8d73TvKZ1UlnZGAT9ZzJ97ZBru07HOPJFVjoipQe2Vfz5Bnd7zDdtuGblw%2FhgP14xuuMMvpep3NOt6wy4R0hjtrZKm3lgS0Q4SmX3uE7OwbnQdWZnAMWTy87SQni36TkL4TJ7EtBxixiO94RNY0Dun4jDMinu8SF8OwTcjHPMh3%2FJHzsRs%2FqEr3jWkrOWF9%2FEAh7m%2FV%2FtIGjcrodZ10oPp6r5Ne4FXed%2BZVHsSVhV3sEtsLHdzSw%2FWtETgT9rDnBo7fsX6%2BT3XSm3%2BpQ12Qt56fPufT9IW%2Ffp3RX35iU%2F7y%2BvkuvLj0AGc4r4SE%2BtFFka2qe0d%2BvYKiEjwycvRXLVmUVDfrCEWBGrXVJaACbVO%2B%2BLKC0R%2FCAjU6lpZDBUa%2BsaO2g%2Fu7LF0jFDo12HmGyrIcjSQSqGmRJWdWluXn6ljWT0GgG5EzuqQA1tfLRlSde9Ps3RKP3ieHyrX2d6QrFGW489IduO%2FjK1Vk0K1%2FFam8v%2F7hiUz%2BBg%3D%3D)
