### ISSUE TITLE
[보류]폴링과 롱폴링의 선택의 문제

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#185]
### 0. 결론적으로 지금 고민하는점 :
쪽지와 알림기능을 폴링으로 할지, 롱폴링으로 할지 어떤것이 더 자원소모량이 적을것인지의 고민

### 1. 불변의 진리 : 
http는 양방향이 되지 않는 모델이다. request, response형태로 단방향만 가능하다.
이러한 단방향으로 실시간 구현을 위한 방법은 2가지가 있는데

### 2. Polling 방식 - 즉시응답방식
클라이언트가 주기적으로 웹서버에게 새로운 내용이 있는지 물어보는 방식
브라우저가 일정한 주기로 HTTP 요청을 보내는 방식
클라이언트에서 주기적으로 체크하는게 폴링
setInterval 메소드로 주기적으로 요청
그러나 실시간 구현에서는 단점을 가진다.
실시간 효과를 내려면 요청의 간격을 줄여야 하지만 서버와 클라이언트 모두에게 부담
http는 단발성 통신이기에 header가 매우 무거운 프로토콜중 하나
이 프로토콜이 과하게 보내진다면 서버에 매우 무거운 부하를 줌
불필요한 다수의 서버 요청으로 서버 및 네트웍 부하가 늘어남

### 3. Long Polling - 지연응답 방식
Long Polling 지연응답 방식은 클라이언트가 서버에게 새로운 내용이 있는지 요청시 
서버에 새로운 내용이 없다면 대답해주지 않다가 새로운 내용이 생기면 대답해주는 방식
HTTP 요청시 서버는 해당 요청을 일정 시간 동안 대기 시킴.
만약, 대기 시간 안에 데이터가 업데이트 되었다면, 
그 즉시 클라이언트에게 응답을 보내고 전달받은 데이터를 처리 후 클라이언트는 바로 서버로 재요청을 시작
이 결과 연결은 무한히 지속 그리고 client는 마치 실시간으로 데이터를 받는 느낌을 받음

폴링과 차이점이 있다면 일반 polling은 주기적으로 물어본다면,
long polling은 일단 보내고 time out될 때까지 무한정 기다린다는 것

롱폴링도 폴링과 마찬가지로 클라이언트에서 주기적으로 요청을 보내지만 
서버단에서 상태값이 변경되기 전까지 응답을 지연시키기 때문에 폴링에 비해 요청/응답 트래픽이 줄어든다는 장점
하지만 마냥 요청을 지연시키는 것 또한 손해이기 때문에 일정시간이 지나면 서버는 요청/응답을 해제

### 4. 도키커뮤니티의 알림과 쪽지, 회원의 접속제한 기능들의 실시간 반영의 간격을 몇초로 얼마나 줄일것인가의 문제

실제로 네이버 카페 같은경우 회원접속 제한과 알림이 실시간 1초내로  반영되고 있음
어떠한 서비스 환경에 있느냐가 이를 결정할것 같다. 네이버의 경우 많은 광고 및 스팸글로 인해 회원 활동정지를 즉각적으로  반영하는것 같았다.
댓글 알림에 대해서도 즉각적인 반응이 되는것보아 이를 회원들에게 서비스하는 차원에서 중요시하게 여기는것 같다. 

그렇다면 도키의 경우? 현재 상황에 맞추어 생각해본다면, 불량회원을 로그아웃 시키는데 1분이 라는 시간이 길어 보이진 않는다.
1분에 한번 폴링 방식으로 요청을 주어 회원을 로그아웃 시켜도, 1분동안 불법 활동을 많이 하는것에는 한계가 있어 보이고 충분히 운영하는데 문제 없어보인다.

그런데 댓글 및 쪽지 알림의 경우 다시 생각해보아야 할것 같다. 도키는 오키커뮤니티의 불편함과 개선을 목적으로 만든 커뮤니티

다. 처음 출발이 그것인데 현재 오키의 경우 알림이 대략 1분에 한번씩 오는 정도, 1분보다는 좀 더 사용자에게 편리함과 서비스의 

질을 높인다면 더 실시간적으로 반영을 하고 싶은데

만약 최소 10~20초 내로 이 실시간 간격을 줄이고자 한다면 이를 폴링으로 할지 롱폴링으로 할지의 고민이다.

쪽지 댓글 알림의 경우 폴링으로 현재 60초에 한번씩 REST 요청이 들어가게 구현해두었는데.

만약 폴링방식으로 10~20초 정도로 계속 요청이 들어간다면 이때 클라이언트와 서버에 미치는 자원 소모량과 

이를 롱폴링방식으로 구현해 데이터의 변화가 생겼을때 즉각적으로 응답이 오게한다면 

이때 미치는 서버에서의 자원 소모량을 비교하기가 어렵다.

이를 어떻게 측정해야할지?

만약에 롱폴링으로 한다면 서버에서 while문이 돌면서 디비의 값이 변화가 있는지를 계속 반복 체크를 하고 있어야 하는데 이때 또한 서버에 부하가 걸리는것이고

이에 대해 자원소모량 측정값이 있어야 비교가 될 것 같은데..

**Comment by ytw9699** [comment]
전체전인 설계

 도키내의 어떤 화면에 리프레쉬가 되면

1. 10초후에 요청이 처음에 들어간다
- 알림의 총갯수를 업데이트해서 보여준다
- 마지막으로 insert된 알림번호도 가져온다

2. 만약 1번이 요청이 성공이라면 다시 롱폴링 요청이 들어간다
- 컨트롤러에서는 화면단에서 넘겨받은 알림번호와 db에서의 가장 최근의 알림번호를 비교해본다 . 
- 알림번호가 변화가 없다면 10초에 한번씩 다시 체크한다
- 이를 변화가 있을때까지 10번을 반복체크 한다
- 체크도중 변화가 있으면 리턴을 해주고 다시 2번의 롱폴링 요청이 들어간다.
- 체크도중 변화가 없이 10번을 반복체크했으면 리턴하고 다시
2번의 롱폴링 요청이 또 들어간다.

3. 기대되는 효과
이렇게 롱폴링을 구현한다면 클라이언트에서 요청이 들어가고 서버에서 다시 응답을 해주는 전체적인 과정이 생략되고
핵심적으로 컨트롤러에서 db의 값이 변화가 됬는지만 10초에 한번씩
체크를 하기 때문에 서버에 부하량을 줄일수 있다고 생각된다.

**Comment by jongfeel** [comment]
### 클라이언트에서 polling 정도의 타이머 돌리는 게 큰 부하가 아니라고 판단됩니다.

- 엄청난 데이터를 주고 받지 않는다는 점 (적어도 채팅과 같이 길이를 가늠할 수 없는 string 값이 아님)
- 지난 번 얘기했던 것 처럼 채팅 서비스나 실시간 성 데이터가 필요하지 않다면 20초에 한번 poling 정도의 부하는 크지 않다고 봅니다.

### Long polling의 경우 DB를 polling 하는 것이 아닙니다.

- 만약 이런 방식으로 구현한다고 가정할 때 클라이언트는 서버 응답만 기다리면 되지만
- 서버가 동시에 응답받은 클라이언트의 갯수가 많아지면 20초 내에 클라이언트의 long polling 요청 만큼 db polling이 일어날 것입니다.
- long polling은 server가 client 요청의 event를 캐치해서 그걸 long polling으로 기다리고 있는 쪽의 client 세션 쪽에 알려주는 걸 만드는 거에요.

**Comment by ytw9699** [comment]
해결한 방향은 폴링도 롱폴링도 아닌 웹소켓으로 해결을 하였고 추후 롱폴링 방식에 대해서도 구현을 한번 해보자 일단 보류
