### ISSUE TITLE
rest api 규약의 고민

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#190]
### 1. 고민하는점
게시글을 스크랩하고, 다시 스크랩을 취소할때의 rest api 규약에 대한 고민

### 2. 현재의 상황
사용자가 게시글을 스크랩 하지 않았으면 , 스크랩을 하고
스크랩이 된 게시글을 다시 스크랩한다면 , 스크랩한것을 삭제하게끔 되어있다.
그런데 이 2가지 경우를 하나의 요청에 모두 묶어둔 상태

https://github.com/ytw9699/Dokky/blob/3a37f8a03d196cac3753092e2b0d81fb2adc2d7f/dokky/src/main/webapp/WEB-INF/views/board/get.jsp#L853-L872

https://github.com/ytw9699/Dokky/blob/3a37f8a03d196cac3753092e2b0d81fb2adc2d7f/dokky/src/main/webapp/resources/js/reply.js#L283-L299

https://github.com/ytw9699/Dokky/blob/61d7a3a9d0ca5abd926fbebc1ad67ee0b3dcbfc5/dokky/src/main/java/org/my/controller/BoardController.java#L360-L385

### 3. 변경 해야 하지 않을까 생각하는점
rest api 규약을 따른다면 post라면 스크랩데이터를 등록을 해야 한다.

그런데 현재 post 요청안에서 경우에 따라 등록도 할 수 있고 삭제도 할 수 있다.

처음 이렇게 만든이유가 사용자가 스크랩 버튼을 눌렀을때 등록도 할 수 있고, 삭제도 할 수 있게 만들기 위해 처음 시작을 잡고 가다보니 만들게 되었다.

그런데 변경해야 한다고 생각하는게 post는 등록 delete는 삭제라는 규약을 따른다면

현재 컨트롤러에서 3가지 경우로 맵핑을 나눠야 하고

1) post scrapData : 스크랩 등록하기

2) get ScrapCnt : 스크랩 등록되어있는지 확인하기

3) delete scrapData  : 스크랩 삭제하기

화면단에서도 
스크랩 등록되어있는지 확인하는 요청을 먼저 보낸후

등록되어있다면 다시 스크랩 삭제요청을 보내고

등록되어있지 않다면 스크랩 등록하는 요청을 보내야 하지않을까 싶다.

문제는 이렇게 되면 한번만 요청을 보내서 효율적으로 처리하던거에 비해서.. 비효율적으로 되지않을까도 싶다.

요청을 보내고 응답을 받고 또 다시 요청을 보내야 하니까..

그런데 rest api를 만드는 규약을 따른다면 현재 처럼 post요청 한번에 post, get , delete 처리를 모두 하는것이 잘못된 방향이지 않을까 싶다.

### 4. 결론

스크랩을 사용자들이 주로 하는 것은 아니기 때문에, 요청과 응답이 반복되어도 크게 부하량에 문제가 되지는 않을것 같다.

그래서 효율적인 처리를 포기하고 rest api 규약을 그대로 따라서 post, get, delete를 모두 분리해서 만드는것이 맞지 않을까 싶다.

**Comment by jongfeel** [comment]
### Check out scrap state

- 상태값이 스크랩 된 상태/스크랩 안된 상태
- 이렇게 나눌 수 있다면 boolean 값 정도로 POST 요청으로 처리가 가능할 것 같습니다.

### Front UI

- 스크랩의 상태가 true/false로 구분 가능하다면 UI button 역시 toggle switch로 두면 어떨까 싶네요
- 그러니까 GET method로 얻어와야 하는 값을 미리 UI에 보여주는 거죠.
- 그 이후에는 UI 값에 따라 On/Off로 구분 될 거고 아래와 같이 UI 값 변경을 할 수 있을 것 같아요.
- On: 스크랩 함 (스크랩 등록을 안한 상태이므로 스크랩 진행)
- Off: 스크랩 취소(삭제)

### REST API Design

- UI에서 미리 Scrap 값을 보고
- POST: 스크랩 등록 요청
- DELETE: 스크랩 취소 요청

이렇게 하면 어떨까요?

핵심은 `게시글에 대한 스크랩의 상태값이 있어야 하고 UI에 보여져야 한다`입니다.

**Comment by ytw9699** [comment]
![image](https://user-images.githubusercontent.com/35983608/87568732-15a12b00-c701-11ea-9c28-7a254c17f72e.png)
완성된 css 토글 버튼입니다.  on, off는 생략했습니다.

**Comment by ytw9699** [comment]
리뷰후

1. 사용자들의 편리함
글을 보고 스크랩을 했던가? 라고 헷갈려 다시 스크랩을 하기전에
스크랩이 되있는 표시를 나타내준다면 스크랩을 안해도 됨

2. rest api 를 만들면서 주의할점

- rest api 메소드의 규약을 꼭 따르는 것은 아니다
애매한거나 이상한것은 보통 post로 하는편
get , delete , put은 명확하지만
post는 범용적으로 쓰는편 항상 생성하는 용도로만 쓰지는 않음

- post 같은 경우 특히 api문서를 더 신경써서 만들어줘야 한다.
post는 넘겨주는 데이터를
파일로 준다는건지
json데이터로 body에 준다는건지
body없이 url 파라미터로 준다는 뜻인지 정확하지가 않다.

그래서 라우터이름을 잘지어야 한다.  파일업로드용이면
fileupload라고 url에 적던가

포맷도 applicaton json 인지
멀티파트 바이너이리인지등등 명확하게있어야한다.
컨텐트타입도 여러가지

post는 범용적이다 보니 정확히 안적으면 뭐하는것인지 알수없음

id에 해당하는 json데이터가 올것이라면
굳이 바디 데이터에 적지말고 파라미터에 적어둘수도 있고

**Comment by ytw9699** [comment]
https://github.com/ytw9699/Dokky/pull/197
