### ISSUE TITLE
2020-09-01, 33th Review meeting - postponed

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#218]
### #216 wireshark로 패킷 검사

이번엔 진행했던 내용 정리한거 위주로 작성하신 듯 합니다.
저는 특별히 할 얘기가 없어서 이번 미팅은 넘어가도 될 것 같은데
혹시 논의하고 싶은 내용이 있다면 코멘트 주시고
다음 미팅으로 넘어가도 된다고 코멘트 주시면
다음 미팅 일정을 정하셔서 그 날짜로 미루겠습니다.

**Comment by ytw9699** [comment]
네 알겠습니다 그럼 2주뒤 다음 미팅으로 넘어갈게요~!

**Comment by jongfeel** [comment]
네 알겠습니다.

사실 dokky service architecture도 제가 예상한대로 잘 그려주신 것 같고
패킷 검사하는 것도 해보면서 결과가 나오는 걸 시간을 두고 보면 좋을 것 같아서 그런 것도 있습니다.

그럼 33th review meeting은 2주 뒤로 하겠습니다.

**Comment by ytw9699** [comment]
네 감사합니다 패킷검사는 좀 더 찾아볼게요~~
