### ISSUE TITLE
33th의 연장 schedule plan

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#221]
# 2주간 총 56 시간

## 평일, 주말, 휴일 상관없이 매일 4시간씩, 횟수 상관 없음.

- 추가로 한번에 집중한 시간이 몇 시간인지에 대한 내용 추가

계획한 시간을 썼는지에 대한 체크이므로, 시간 체크를 잘 해주세요.

**Comment by ytw9699** [comment]
- [ ] 9/2 4시간
- [ ] 9/2 4시간
- [ ] 9/2 4시간
- [ ] 9/2 4시간

**Comment by jongfeel** [comment]
33th에서 실제 미팅을 진행하지 않았으므로 33th의 연장이라고 봐야 할 듯 합니다.

**Comment by ytw9699** [comment]
네 알겠습니다~
