### ISSUE TITLE
로컬호스트의 구분 방법에 대해

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#222]
### 1. 서버에서 s3로의 접근 방법( s3객체의 생성방법)

https://github.com/ytw9699/Dokky/blob/test/dokky/src/main/java/org/my/s3/myS3Util.java

- 로컬호스트의 경우 : db에서  s3로 접근가능한 access key를 불러와 s3로 접근한다.
- ec2 :  access key없이 그냥 바로 접근가능하다 왜냐하면 권한 설정을 미리해두었기 때문

### 2. FileCheckTask 클래스의 역할

https://github.com/ytw9699/Dokky/blob/test/dokky/src/main/java/org/my/task/FileCheckTask.java

현재 FileCheckTask 클래스의 역할은 주기적으로 업로드 파일을 비교 정리한다.

이 정리는, 먼저 디비에 입력된 업로드 목록과, s3에 실제 업로드 되어 있는 목록을 비교를 하여 

디비에는 없는 파일이 s3에 업로드 되어 있다면 s3에서 삭제를 해준다.

왜 이러한 스케쥴 작업을 하냐면

사용자들이 글쓰기 버튼을 누른후 파일을 업로드하고 나서 글 등록 버튼을 누르지 못하고

종료가 되거나 브라우저를 닫아버리면 s3에만 실제로 업로드 되어있고 디비에는 입력되지 않기 때문이다.

즉, 불필요한 파일들이 s3에 쌓여가기 때문에 이를 주기적으로 점검하여 삭제를 하고 있다.

그런데 이 작업이 클라이언트가 요청을 줘서 삭제를 하는 것이 아니라, 서버 자체가 돌면서 일정한 시간에 처리를 하고 있다.

그러다 보니 생기는 문제가 현재 돌고 있는 서버의 테스트 환경이 로컬호스트인지? 아니면 dokky서버인지를 구분하기가 어렵다.

if(request.getServerName().equals("localhost")){

}

그래서 구분방법으로 os의 이름을 알아내어 우분투인지 윈도우인지로 구분을 해보았는데, 이는 한계가 있다.

String osName = System.getProperty("os.name");

만약 이 프로젝트를 사용하는 사람의 로컬호스트 환경이 윈도우가 아니라면 , 이에 맞춰 코드를 또 수정해주어야 한다.

**Comment by jongfeel** [comment]
FileCheckTask에 대한 의견

- 글쓰기 버튼을 누를 때 파일 업로드를 처리하면 안되는 걸까요?
- 안된다면 어떤 이유 때문에 그런 걸까요?

**Comment by jongfeel** [comment]
글쓰는 중에 사진 추가한 것과
첨부 파일로 추가한 것 모두
S3로 업로드 됨.

**Comment by jongfeel** [comment]
글쓰기 중에 임시로 저장한 사진 파일의 경우
특정 이벤트가 발생할 때 임시로 저장한 S3의 파일을 삭제 - 취소 버튼, 브라우저 종료, 다른 페이지 이동

**Comment by jongfeel** [comment]
도커 이미지를 만들어서 로컬 배포 환경이나 EC2+S3 배포 환경을 구성하는 것도 나쁘지 않음
