### ISSUE TITLE
글 쓴 날짜 및 시간 나타내기 변경

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#224]
https://github.com/ytw9699/Dokky/projects/3#card-35522259

기존의 문제점:

- 만약 8/30일날 글을 쓰고 9/2일날 확인해보면 1달전으로 나타내고 있었다.
- 3일전 밖에 안되는 기간임에도 불구 1달전으로 표기하는 문제점
- 년수 표기도 마찬가지

변경후:  

이전달의 말일을 계산 (8월의경우 31일) +  9/2일(2일) - 8/30(30일) = 3일
31 + 2 - 30 =3일

년수도 변경

1~3주 전도 계산

https://github.com/ytw9699/Dokky/commit/79de545e96ab3fb7c203824c195ed040573bbf20

**Comment by jongfeel** [comment]
날짜 계산하는 코드가 길게 나왔는데
Java에 Period와 Duration을 사용하면 많은 if문을 사용하지 않고도 제법 깔끔한 코드를 작성할 수 있을 겁니다.

https://docs.oracle.com/javase/tutorial/datetime/iso/period.html

**Comment by jongfeel** [comment]
javascript라면 특별히 제공되는게 없어서 별도의 라이브러리를 써야 하는 것 같네요.

https://github.com/mstum/TimeSpan.js?files=1

요게 괜찮아 보입니다.
