### ISSUE TITLE
채팅 서비스 문서(웹소켓을 활용)

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#228]
### 1. 채팅의 필요성
- 사용자들의 편리성을 위해(타인에게 노출되지 않는 개인들간의 소통 방법 및 가장 실시간성이 반영되는 대화)
- 커뮤니티의 특성은 회원들간의 소통이 중심
- OKKY커뮤니티에는 존재하지 않는 기능 

### 2. 벤치마킹 
- 네이버 카페 채팅과 카카오톡과 유사하지만, 가장 필요하고 핵심적인 기능을 구현

### 3. 요구사항

- 1 ) 채팅방 화면   chatRoom.jsp
- 2 ) 채팅리스트 화면 chatRoomList.jsp

##### 1:1채팅 (텍스트만)
- 상대방과 1:1채팅 시도시 자동으로 상대방을 방에 초대한다
- 1:1채팅방 화면에서 초대를 하면 그룹채팅으로 전환된다.

##### 그룹채팅 (텍스트만)
- 회원의 수를 자유롭게 선택하여 채팅방을 만들 수 있고, 만드는 즉시 타 회원들을 초대한다
- 방장만 다른사람을 방에서 내보낼 수 있다.
- 그룹채팅을 만들시 방 제목을 설정하지않으면 방인원의 닉네임을 조합해 방제목이 만들어진다.

##### 채팅방 공통사항
- 중복로그인이 가능하기 때문에 채팅 또한 중복으로 할 수 있다.
- 방장을 제외한 사람들도 다른사람들을 1명이상 초대할 수 있다.
- 채팅룸에서 채팅내용을 읽지 않은 채팅멤버의 수를 숫자로 보여준다.
- 채팅방 에서 나갈 수 있다.
- 다른사람을 초대하거나 방에서 나갈시에는 채팅방에 공지로 알려준다
- 채팅방을 나가면, 나간사람의 경우 이전의 채팅내용을 읽을 수  없다.
- 다른사람에게 채팅이 왔을때 채팅방 스크롤이 맨 하단에 있지 않다면 새로운 채팅내용을 띄어주고 사라지게 한다
- 다른사람에게 채팅이 왔을때 채팅방 스크롤이 맨 하단에 있다면 새로운 채팅내용을 만들고 다시 스크롤을 맨 하단으로 내린다
- 채팅내용을 전송시 스크롤을 맨 하단으로 내린다
- 채팅내용은 DB에 보관되어 다시 읽어들일 수 있다.
- 채팅방에서 채팅내용의 날짜를 구분선으로 표기 하고, 오늘 날짜는 년월일 없이 시간만 나타낸다(카톡과 같은 기능)

#### - 채팅 리스트 화면 요구사항(카톡과 거의 유사)
- 만들어둔 채팅방 리스트를 볼 수 있다.
- 채팅방의 리스트는 최신 메시지 순으로 나열된다.
- 채팅리스트에서 채팅방을 선택하여 나갈 수 있다.
- 채팅방 마다 마지막 메시지를 간략히 보여준다.
- 채팅방 마다 마지막 메시지의 시각을 보여준다
- 채팅방 마다 읽지 않은 메시지의 갯수를 보여준다.
- 채팅방 리스트 화면에서 초대버튼을 클릭하여 1:1채팅과 그룹채팅 방을 만들 수 있다.

#### 사이트 전체 공통사항(common.jsp)
- 읽지 않은 채팅내용의 갯수를 실시간으로 보여준다.

### 4. 서비스 설계도
[설계도](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1#R7Vxdc6M2FP01nmkf4kESCPyYOJtsd5N2W2%2Bb7L50CCiYGiOvwLHdX19hBAahOI6NwVPjF6MruAKdo3t0xUcPDafLW2bPxvfUJUEPau6yh657EEINmPwvsaxSC9AhTi0e811h2xhG%2Fr9EGDVhnfsuiUo7xpQGsT8rGx0ahsSJSzabMboo7%2FZMg3KrM9sjFcPIsYOq9cF343FqtaC5sX8kvjfOWgZ4kNZM7WxncSXR2HbpomBCH3poyCiN063pckiCpPeyfnn4ZfUQ3E3w7affox%2F2n1efv%2F7610Xq7OY9h%2BSXwEgY7%2B3anv6D7ZuQXUzib97dp%2B%2Fenbe8EFi%2B2MFc9FcP4oA3cvVMeVv8ouOV6En8Y06ziotojfMl3wFps%2BWmkm95yf81nUxWCapjO4790Es8EfbiO4RvXTJn7Mcc7DkjWXP8vNMW0%2BNFj%2BeNw5gsE3sUMzohQxpQxu0hDUlyRn4QSKZxPA14CYjzFbSEelYWjpP6F8Jin%2FPlMvC9kNumvusmlVe2MDi81wnLT%2BpNGARciV%2ByLJBQwHJL6JTELOmdrBaYRnqMGGRIMG6xISwwsgE1LrBVFzZbDBIv970hAt8QXHgHLwA6mBjQUBEj8%2FKUGYaBT9a4ZzR4quzKZMtbZFkk9BrNbCcpL3hgKzPCjmZppHn2l8SVCNSD6Gb9OyLglqmV8AagCngedop458ZDAPf%2B%2FvwR3Dq%2FfR%2F9gF9HxiMJsSNiRxN484hQRXbIfTEaBISdMhMqCO9KjteZgMtMwFbrTABNMeH66rywBnlcX2XRu3WwYbvD%2FoE8RdSZEEXV2A7dswsHAMOTU4YGZgIKF0%2B2M%2FEYnYfuhZMCkHiKmR1Goo8rDtUUG2XTzvPiEZB0xWidR6pUQ%2BpWErqXScqXTLoDO4p8p9yv6QHErWR8u03QIjpnDnmL6tVOLfSZoeiyzMZIYMf%2BS%2FncVN0oWvhC%2FfX4yXNtrYyZha2yj%2FT8xWHFTE%2FyBAaS0GA5T4ht5pG44ol3vr0q7DZLdoheP2UwgGqabXiSutywJu%2FW%2FYlkNaVZ93xcQ2xPk9G9rhnFbJ3LDkVm%2Bwel03wPOYCcQ5gZ6NKMZqDKXBVjJjfWHmYGTbGDE4AJApwR5BBJypILRnuQA1XK8k5pIUs%2Ffixsf%2BPbWh8gJMrXyfVrWWFVKHwhzOfXkawQrW3HFimrVZEC0og3ZFR3FSmeDElEsoydRKouGQGN5T5dpEjFARitR4rGljU7zNMJ4QlgXkPiwfuErR6zoJ8UUn3AWXEjD%2BvSqliSBUItNdDYqjSNqApPsNcx982o2Zr8QG3QHxR%2B5fsmGEoSsrsY4W1%2BEd4tf6pNmsw6KdvXAJJoq8GDiJt5zMmLdfM050m7MLrdrB%2FArYw2YH9vTm8dK4bZ8HSrsbR9pFpOLifyi2zdeUT4yKHhOSfx0JCm9ABWNRtqiiGQG%2BvXbFUWX0tGd0yZbS2G6Ma2kQ4PiCEyNyBoNmpkiwvHjxpRHgnOaexbEr5m64s5ULWY0%2BnECXBFjgW61rpOZLLQkeXUyYJx%2B2SpYyGgm1QIoYD1TSpwwyu%2FsI70uiNC1orVl1PJvZmgm6Avr%2BEcmwyqvLQjw2uImbq%2BLdXQ9o8KFiz7ArhhIjR25%2FhMUw1DSiWN1m8NoC67bDS71BVPoTUN%2BdGeFfh%2Fhnvp%2BXQ%2BV9tf7S0k3VaBjas9Ut0A7uB%2FXe3L8CO0P%2FZSKNAbBl5vKtSf%2FgtN9Ud6BKT7%2FqZC23VVoK%2FjDTY14EYHeIOAQ6yQ9oYRP%2Fxl1g7x3RHXFSt6TSPeLeS8Q82RJr9cpJv7ZusISE9v5uxoSs%2B7ZZt3QS8NXiSvsu8MvGZJk%2Fjq3eVjQ989HHAI9Pk7GgdDb%2BhNQ6%2FDCvRiZaUfccjv%2BbbtkZ9%2BrvBBfD6iwIBdvyRR%2BQrEq9%2BLUCn4%2Bg3GRK%2FXBCp8igJpx9RqOdJjxexsoODcHi%2F%2F8eLmEygpzpsvyaAP%2FwE%3D)

설계도에서 핵심은 웹소켓 세션 객체를 채팅룸 객체마다 나눠서 관리한다는것

![image](https://user-images.githubusercontent.com/35983608/93110822-c8d1d480-f6f0-11ea-9ab0-9742b2f59d97.png)

### 1)  채팅룸 테이블 -----------------------------------------------------

create table dk_chat_room(
 
		 chatRoomNum number(10,0), --기본키 pk
		 chat_title VARCHAR2(50), -- 방 제목
		 roomOwnerId VARCHAR2(50) NOT NULL, --방장 아이디
		 roomOwnerNick VARCHAR2(50) NOT NULL, --방장 닉네임
		 chat_type number NOT NULL, -- 0 = 1:1채팅방 , 1 = 그룹 채팅방
		 headCount number NOT NULL, -- 방의 총 인원수
		 constraint pk_chat_room PRIMARY KEY(chatRoomNum)
)

create sequence seq_dk_chat_room;

채팅룸 

필드명 | 설명 | 자료형식
---- | ---- | ----
chatRoomNum | 채팅방 번호 | Long
chat_title| 방 제목 | String
roomOwnerId | 방장 아이디 | String
roomOwnerNick | 방장 닉네임 | String
chat_type | 채팅방의 타입 ( 0 = 1:1채팅방 , 1 = 그룹 채팅방)  | Int
headCount | 방의 총 인원수 | Int

### 2) 채팅룸의 멤버 테이블 -----------------------------------------------------

create table dk_chat_member(
 
		 chatRoomNum number(10,0) not null,--fk
		 chat_memberId VARCHAR2(50) NOT NULL, -- 채팅룸 멤버 아이디
		 chat_memberNick VARCHAR2(50) NOT NULL, -- 채팅룸 멤버 닉네임
		 recentOutDate date, --방에서 나간 최근 날짜
		 present_position number default 0, --(현재 멤버의 위치) 0 = 방에서 안나감 , 1 = 방에서 나감
		 constraint fk_chat_member foreign key(chatRoomNum) references dk_chat_room(chatRoomNum) on delete cascade
)

채팅룸의 멤버

필드명 | 설명 | 자료형식
---- | ---- | ----
chatRoomNum | 채팅방 번호 | Long
chat_memberId | 채팅룸 멤버 아이디 | String
chat_memberNick | 채팅룸 멤버 닉네임 | String
recentOutDate | 방에서 나간 최근 날짜 | Date
present_position  | 현재 멤버의 위치(0 = 방에서 안나감 , 1 = 방에서 나감) | Int

### 3) 채팅 내용 테이블-----------------------------------------------------

create table dk_chat_content(
 
		 chatContentNum number(10,0), --pk
		 chatRoomNum number(10,0) not null, --fk
		 chat_content varchar2(4000) not null, --채팅 내용
		 chat_writerId VARCHAR2(50), -- 글쓴이 아이디
		 chat_writerNick VARCHAR2(50), -- 글쓴이 닉네임
		 content_type number default 0,  -- 채팅 내용 종류 (0 = 일반내용 , 1 = 공지내용)
		 readCount number,  -- 현재 읽지 않은 인원수
		 regdate date default sysdate, 
		 constraint pk_chat_content PRIMARY KEY(chatContentNum),
		 constraint fk_chat_content foreign key(chatRoomNum) references dk_chat_room(chatRoomNum) on delete cascade
)

create sequence seq_dk_chat_content;

채팅 내용

필드명 | 설명 | 자료형식
---- | ---- | ----
chatContentNum  | 채팅 내용 번호 | Long
chatRoomNum | 채팅방 번호 | Long
chat_content  | 채팅 내용 | String
chat_writerId | 글쓴이 아이디 | String
chat_writerNick | 글쓴이 닉네임 | String
content_type | 채팅 내용 종류 (0 = 일반내용 , 1 = 공지내용) | String
readCount | 현재 읽지 않은 인원수 | Int
regdate | 입력날짜 | Date

### 4) 채팅 내용 읽음 여부 테이블-----------------------------------------------------

create table dk_chat_read(
 
		 chatReadNum number(10,0), --pk
		 chatContentNum number(10,0) NOT NULL, --fk
		 chatRoomNum number(10,0) NOT NULL, --fk
		 chat_memberId VARCHAR2(50) NOT NULL, -- 채팅룸 멤버 아이디
		 chat_memberNick VARCHAR2(50) NOT NULL, -- 채팅룸 멤버 닉네임
 		 read_type number default 0, -- 메시지 읽음 여부 (0 = 읽지않음 , 1 = 읽음)
		 constraint pk_chat_read PRIMARY KEY(chatReadNum),
		 constraint fk_chat_read_first foreign key(chatContentNum) references dk_chat_content(chatContentNum) on delete cascade,
		 constraint fk_chat_read_second foreign key(chatRoomNum) references dk_chat_room(chatRoomNum) on delete cascade
)

create sequence seq_dk_chat_read;

채팅 내용 읽음 여부 

필드명 | 설명 | 자료형식
---- | ---- | ----
chatReadNum | 채팅 내용 읽음 여부 번호 | Long
chatContentNum  | 채팅 내용 번호 | Long
chatRoomNum | 채팅방 번호 | Long
chat_memberId | 채팅룸 멤버 아이디 | String
chat_memberNick | 채팅룸 멤버 닉네임 | String
read_type | 메시지 읽음 여부 (0 = 읽지않음 , 1 = 읽음) | Int

### 5. 설계와 구현의 어려운점

- 핵심적인것은 웹소켓 세션을 어떻게 분리해서 관리,유지를 할것인가가 가장 큰 복잡성

- 채팅을 여러명 정도가 한다면 하나의 map 객체 안에 , 사용자들의 웹소켓 세션 객체를 모두 관리할 수 있을것 같은데
수십,수백,수천명이 된다면 ? 하나의 채팅방마다 chatRoom 이라는 객체를 만들어두고  이를 관리하는 chatRoom map을 또 만들고, 이 chatRoom 안에 특정 사용자들의 웹소켓 세션 객체를 관리하는게 좋다고 판단이 된다. 
왜냐하면 하나의 map안에 모든 웹소켓 세션 객체를 관리한다면 , 그 객체를 찾아오는 시간도 부하가 많아질것 같기 때문

- 클라이언트가 끊겼을 경우에도, 불필요 웹소켓 세션에 대한 삭제 및 관리가 계속 필요하고 유지되어야한다.
- 1:1채팅보다 그룹채팅을 같이 설계하려다보니 굉장히 복잡스럽다
- 웹소켓 핸들러의 분리(하나로 통합?  2가지를 쓸것인가?)
답은 일단 2가지로 나누는게 추후 관리가 편하지 않을까? 하지만 어디선가 낭비가 없는지를 잘 생각해봐야 할것 같다.

- 채팅룸객체와, 세션객체들을 담아두는 자료구조를 어떤것을 쓸것인가?
map인가, list인가, set인가 이에 대한 이유와 결정이 필요

### 6. 느낀점

1 ) 웹소켓 채팅을 처음 구현하다보니 감이 아직 없다. 그래서 설계를 하려다보니 막막하여 어느정도 다시 코딩, 테스트를 해보고,

다시 돌아와 또 설계를 하고 이러한 과정을 반복하며 잡아가고 있다

만들어보고 구현해본것을 다시 설계를 해보려한다면 할 수 있을것 같은데, 생소한것을 설계하려니 복잡하다

2 ) 스프링의 특징에 대해 다시 보고 있다.

스프링은 싱글톤으로 객체들을 유지하고 이를 가져다 쓰는것에 대한 인지가 부족했고, 이를 직접적으로 더욱 느끼고 있다

chatWebsocketHandler 와 ChatController에서 ChatServiceImpl 객체를 같이 공유

### 7. 구현 및 테스트

https://github.com/ytw9699/Dokky/issues/233

**Comment by jongfeel** [comment]
중복 로그인 기능에 대한 고려 필요
- 중복 로그인이 허용된다면 Map 사용 못함, 다른 방식으로 진행
- 중복 로그인이 안되게 추가 구현 한 후에 Map 사용
