### ISSUE TITLE
Create new to do issue

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#232]
#231 에 보면 지금까지 총 5.5 시간을 쓰셨는데 어떤 일을 하는데 썼는지 내용이 있어야 합니다.

그래서 하셨던 일에 대해 issue로 등록하고 project에 In Progress로 해 둔 후에 진행해 주세요.

**Comment by ytw9699** [comment]
네 이슈 등록해두었습니다.

https://github.com/ytw9699/Dokky/issues/233
