### ISSUE TITLE
웹소켓 채팅 구현중

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#233]
### 웹소켓 채팅 구현 중인 핵심 코드

1. ChatController
https://github.com/ytw9699/Dokky/blob/test/dokky/src/main/java/org/my/controller/ChatController.java

2. ChatServiceImpl
https://github.com/ytw9699/Dokky/blob/test/dokky/src/main/java/org/my/service/ChatServiceImpl.java

3. chatWebsocketHandler
https://github.com/ytw9699/Dokky/blob/test/dokky/src/main/java/org/my/handler/chatWebsocketHandler.java

4. 채팅방화면 및 채팅리스트 화면
https://github.com/ytw9699/Dokky/tree/test/dokky/src/main/webapp/WEB-INF/views/chat

채팅방 초안
![image](https://user-images.githubusercontent.com/35983608/94459783-cc865080-01f2-11eb-8900-a89705478c9e.png)

5. ChatMapper.xml
https://github.com/ytw9699/Dokky/blob/test/dokky/src/main/resources/org/my/mapper/ChatMapper.xml

### 요구사항의 추가 및 테이블 변경 ( 구체적으로 )
https://github.com/ytw9699/Dokky/issues/228

### 코딩과 설계의 비중
설계를 한 후에 그에 맞게 코딩을 하면, 다시 수정해야할 설계 및 요구사항이 끊임없이 생겨난다..
여기서 설계에 힘( 전체적인 그림을 계속 생각)을 더 줘야할지, 코딩에 힘을 줘야할지..
설계를 하고있자니 너무 복잡하고 더이상 보이는 부분이 없을때가 있다. 그러다
코딩을 해보고 나면 설계를 수정 해야할 부분들이 명확하게 보인다. 그런데
설계를 안하고 코딩을 하면 , 시행착오와 비효율성이 생기는것 같다..
설계를 하고있다보면 복잡하고 예측만 하는거 같은 답답함에 코딩을 하고나면 보이는 부분들이 
생겨서 조금더 코딩쪽으로 비중을 두고있다.

### 1:1채팅과 그룹채팅
-1:1채팅만 생각하면 편한데, 그룹채팅을 같이 한번에 만들자니 너무 복잡성이 커지고 엄두가 안남..
그래서 1:1채팅부터 일단 만든후에 다시 그룹채팅을 추가하는 방식으로 구현을 하는방식을 선택
이렇게 구현을 하다보면 단점으로는 분명 1:1채팅에 맞춰서 만들기 때문에 그룹채팅을 위해 수정해줘야 하는 부분들이
생겨 비효율성이 생기지만 처음 만들어보는 채팅이라 설계의 접근이 어렵기 때문에 선택

### 앞으로 구현해야할 우선순위들을 세워보자

-  일단 1:1 채팅방부터 완성해보자
- 채팅메시지 읽음 처리 인원수 표시
- 방에서 나갈시 이전의 채팅내용 볼 수 없게 하기
- 채팅방에서 채팅내용의 날짜를 구분선으로 표기 하고,  오늘 날짜는 년월일 없이 시간만 나타내기(카톡과 같은 기능)
- 그룹채팅(초대 , 내보내기, 방제목 설정하기)
- 채팅리스트 만들기( 만들어진 채팅방의 목록)

**Comment by jongfeel** [comment]
달아주신 project card link가 이제는 issue 기반으로 되면 됩니다.
