### ISSUE TITLE
Propose to do work list and make issues

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#235]
## No update issue body

github에서 히스토리 보기 기능을 지원하기는 하지만 일일이 클릭해서 봐야 하는 번거로움이 있습니다.
지금 #233 issue의 경우는 수정을 19번이나 했는데 이걸 다 일일이 추적하면서 보기에는 상당한 어려움이 있어요
![image](https://user-images.githubusercontent.com/17442457/94518183-6c2ff700-0264-11eb-942d-557f8a210db9.png)

그래서 업데이트가 일어나면 새로운 issue로 만들던가 comment를 달아서 업데이트 된 내용이 뭔지 기록하는게 좋을 것 같습니다.

만약 최종 정리된 문서로 만들어야 하는 issue라면 issue에는 간략하게 링크만 달고
실제 문서는 wiki 페이지나 기타 다른 문서의 링크를 다는게 낫습니다.

물론 그 작업을 하는 문서도 작은 단위의 commit으로 commit history로 남기는 것이 좋습니다.

## Make check point

태원님의 경우는 협업을 안해보셔서 열심히 작업한걸 만들어 놓고 보여주는게 맞다고 생각하실 수도 있는데요.
이렇게 추측한 근거는 #234 에 pull request를 self로 하셨으니까 혼자 진행한 걸로 업데이트를 하셨거든요, 그런데 이렇게 pull request 할꺼면 그냥 master branch에 commit 하는게 더 낫지 않을까요?

commit의 횟수가 14번이나 된다면 충분히 코드 리뷰를 할 수 있는 타이밍도 있었을 테고
commit 마다 작업 단위를 issue로도 관리해서 점진적으로 진행할 수도 있었을 겁니다.

또 #233 에서 소스코드 링크를 별도로 붙였다는 건 진행중인 코드 리뷰가 아니라 완성본의 코드 리뷰를 원하시는 듯 한데
이건 코드리뷰를 하기 어렵습니다. 코드를 수정한 부분과 그 코드를 수정한 작업의 내용이 일치가 되어야 context를 따라갈 수 있기 때문입니다.

## Propose

- 하나의 작업 단위를 issue로 만들고 그걸 commit 단위로 만들어 주세요. 어렵다면 2~3 commit 단위로 해도 괜찮습니다.
- 문서 작업도 issue로 계획을 세우고 난 뒤에 문서 작업을 진행해 주세요. #233 이라는 제목은 해당 기능들의 체크 리스트가 나오는게 맞는데, 최종적으로는 회고 문서로 변경되었으니까요. 이 부분은 역시 별도의 문서 작업으로 진행되는게 좋습니다.
- 이미 잘 실천하고 계신 진행 시간 계획하고 엮어 보면 매일 4시간 진행 계획에 대해 이미 계획이 있으므로 4시간 분량 단위로 할 일을 미리 issue로 만들어 두고 진행하고 진행한 이후 변동 상항을 새로운 issue로 만들면서 진행하면 자연스럽게 됩니다.
- 즉, #233은 최초에 할일 목록이 나와 줬어야 했고, 진행하는 과정에서 추가 및 변경이 일어나는게 자연스럽습니다.
- 그러는 와중에 이미 만들어진 issue에 대해서 폐기 되거나 필요 없어지거나, 다른 issue로 대체되거나 하는 사항이 생기면 close 시키고 계속 새로운 issue들로 작업을 진행하시면 됩니다.

## Any questions

- 질문할게 있으면 comment 달아주세요.

**Comment by ytw9699** [comment]
네 무슨말씀이신지 이해되었습니다. 

이번에 진행을 하면서 코드리뷰요청 시기를 놓쳤습니다..

평소와 다르게 계속해서 설계와 코딩에서 변경점이 너무 많고 혼동스러워 수정사항이 굉장히 많았습니다.

어느정도 큰 뼈대를 잡고서 코드리뷰를 요청할려하다보니 이렇게 됬네요..

위 말씀대로 다시 진행해보겠습니다.
