### ISSUE TITLE
34th review meeting 관련

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#245]
이번 리뷰때 까지

https://github.com/ytw9699/Dokky/issues/236

말씀해주신 방식처럼의 리뷰할 이슈는 나오지 않았습니다.

https://github.com/ytw9699/Dokky/issues/240#issuecomment-703710813

현재 위 부분에서 어려움을 겪고는 있으나, 조금 더 시간을 가지고 해결 해본후

이슈를 올려보려 합니다.

**Comment by jongfeel** [comment]
네 알겠습니다.

부담갖지 마시라고 다시 알려드리면

기존
- 공부하고 구현해야 할 내용을 진행하고 issue로 정리
- 그 내용을 제가 확인하고 같이 리뷰하는 형태
- 제가 적극적으로 개입을 했기에 상대적으로 저와 어떤 얘기를 해야 하는지 준비가 잘 안되있는 상태
  - 즉, 진행한 내용은 있지만 거기서 무엇이 더 필요하고 알아야 하는지에 대한 내용이 들어가지 않았기 때문에 제가 즉흥적으로 온라인 미팅을 하면서 얘기해 드린 형태
  - 이렇게 하다 보면 제가 빠뜨리는 경우도 있고 얘기하면서 나온 추가적인 내용이 comment로 잘 등록이 안되는 경우가 있음

변경
- 공부한 내용 정리나 혼자 진행하면서 정리한 내용은 그대로 issue에 정리
- 리뷰 미팅 전에 얘기하고 싶은 부분에 대해서 issue로 적고 각 issue나 pull request 링크들을 추가하여 참조
- Assignees를 반드시 저를 할당
- 어떤게 필요하고 어떤게 부족한지 스스로 체크하고 얘기할 수 있는 긍정적인 부분을 이끌어내기 위함

**Comment by jongfeel** [comment]
그러면 다음 미팅은 언제 하는게 좋을지 알려주세요.

**Comment by ytw9699** [comment]
네 1주더 미뤄 보는게 좋을거 같아요~! 

13일입니다.
