### ISSUE TITLE
[보류] 웹소켓의 오류

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#246]
### 1. 들어가는 요청 2가지

- new WebSocket("wss://dokky.ga:443/commonWebsocketHandler"); // 공통 웹소켓
- new WebSocket("wss://dokky.ga:443/chatWebsocketHandler"); // 채팅 웹소켓

### 2. 겉으로 드러난 현상

WebSocket connection to 'wss://dokky.ga/commonWebsocketHandler' failed: Error during WebSocket handshake: Unexpected response code: 500

![image](https://user-images.githubusercontent.com/35983608/95346787-2a075500-08f7-11eb-888f-42912365423a.png)

WebSocket connection to 'wss://dokky.ga/chatWebsocketHandler' failed: Error during WebSocket handshake: Unexpected response code: 500

![image](https://user-images.githubusercontent.com/35983608/95347755-363fe200-08f8-11eb-9e47-7162e3021f9c.png)

겉으로 드러난 이 오류들이 광범위하기 때문에 정확한 원인이 무엇인지 알 수 없음.

### 3. 내부적인 문제점의 위치 추정

화면단에서 아파치 서버로 요청이 들어갈때 맵핑을 하지 못하는 것 같다.
화면단에서 아파치 사이 시점의 문제라고 생각하는 이유는 톰캣 로그에서 어떠한 로그도 찍히지 않는다.
즉 톰캣 까지 들어오지를 못했기 때문

- 화면단에서 new WebSocket("wss://dokky.ga:443/commonWebsocketHandler"); 요청이 들어가면

- 다시 아파치로 들어가는데 설정 부분에서 아래와 같이 잘 잡혀있다. 그런데 요청을 받아 들이지를 못하는것만 같다.

![image](https://user-images.githubusercontent.com/35983608/95347358-c0d41180-08f7-11eb-8590-a4ddb5cec57f.png)

wss://dokky.ga:443/commonWebsocketHandler 이 요청을

다시 wss://dokky.ga:8443/commonWebsocketHandler 로 재요청하는데

지금 까지 아무 문제도 없었는데 갑자기 이러한 현상이 발생..

서블릿 설정에서도 URL 맵핑이 잘 되어있음

![image](https://user-images.githubusercontent.com/35983608/95348118-ababb280-08f8-11eb-9bd5-92a0eab1f083.png)

- 포트 설정도 문제없음

443으로 들어온걸 다시 8443으로 요청 들어가는 곳도 리슨을 해주고 있고

![image](https://user-images.githubusercontent.com/35983608/95348265-d269e900-08f8-11eb-96fe-326a4d01bd4e.png)

- ec2 인바운드 규칙 또한 문제없이 8443에 ec2가 접근 가능하게 되어있음
![image](https://user-images.githubusercontent.com/35983608/95348458-07763b80-08f9-11eb-9619-1ab40bda0f8d.png)

- 전체적인 요청의 과정에서도 문제될것이 없음

![image](https://user-images.githubusercontent.com/35983608/95348796-5a4ff300-08f9-11eb-80d2-55ae6180bb2c.png)

- 코드를 업데이트 하고 나서의 문제일까 의심이 들어 잘 돌아가던 시점의 브랜치를 새로 따서
돌려보아도 같은 현상

- 분명한건 로컬에서 톰캣만으로 프로젝트를 돌리면 아무 문제없이 잘 돌아가고
ec2에서 돌아가지 못하는것으로 보아 또 환경차이로 인해 어떠한 설정의 문제인것 같은데 원인을 찾기 쉽지 않음
설정을 건드렸다면 의심해볼만 하지만 설정도 건드리지 않았고, 코드도 이전의 시점으로 되돌려 돌려보아도 나타나는 이 현상은
어떻게 해석해야할지..

- 아파치 로그 확인
 tail -f /var/log/apache2/error.log

[proxy:error] [pid 4531:tid 139898963097344] (502)Unknown error 502: [client 59.15.128.100:14641] AH01084: pass request body failed to 13.125.253.147:8443 (dokky.ga)

[proxy:error] [pid 4531:tid 139898963097344] [client 59.15.128.100:14641] AH00898: Error during SSL Handshake with remote server returned by /chatWebsocketHandler

-  proxy 설정 확인 - 문제없음
a2enmod proxy_wstunnel
![image](https://user-images.githubusercontent.com/35983608/95589874-526e8b00-0a80-11eb-8ce3-f60c13e80975.png)

- 아파치 버전 2. 4. 29 확인
![image](https://user-images.githubusercontent.com/35983608/95804119-c50b8f00-0d3c-11eb-9f3f-8e2d5002d41a.png)

- 설정의 추가

![image](https://user-images.githubusercontent.com/35983608/95804331-61ce2c80-0d3d-11eb-95e5-3e128a7afd6c.png)
백엔드 서버가 오래된 자체 서명 된 인증서를 사용하는 경우 하나 이상의 옵션이 필요하다는것?
(백엔드 서버에 접근이 없는 경우?)

https://serverfault.com/questions/538086/proxyerror-ah00898-error-during-ssl-handshake-with-remote-server

- 설정 추가시 문제가 해결

- 문제는 해결됬으나 정확한 원인은?

ssl + 프록시를 사용할때 발생하는 문제같은데, 오래된, 옛 버전의 자체 서명 인증서를 사용하면
Peername 등의 어떠한 항목들의 체크가 계속 이뤄지고, 그래서 이 기간을 off 해야 한다는것?

그렇다면 지금까지 문제가 발생하지 않다가 발생한 이유는?
특정한 기간이 지나면 그때부터 체크를 하기 때문에 이 기간을 off 해야 하는것인지

**Comment by jongfeel** [comment]
인증서 데이터를 확인해서 expire date 문제인지 분석해 보면 어떨까요?

**Comment by ytw9699** [comment]
인증서 만료날짜의 경우 아직 기간이 남아 문제는 없는것 같고, 

다른 제한을 거는 무언가 있을수 있음

- 일단은 해결해서 잘 돌아가니, 다른 급한거 부터 해결하기위해 보류
