### ISSUE TITLE
채팅 내용 데이터 조회의 쿼리 변경 방법

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#247]
### 기존

![image](https://user-images.githubusercontent.com/35983608/95756858-51886400-0ce1-11eb-8b58-2fd2d94de28a.png)

<select id="getChatContents" resultType="org.my.domain.ChatContentVO"> 
				  	  select /*+INDEX_ASC(dk_chat_content pk_chat_content) */
				  	  												  chatContentNum	
								     								, chat_writerId
															    	, chat_writerNick
															    	, chat_content
															    	, content_type
															    	, regdate
															    	, readCount
								from dk_chat_content 
								where chatRoomNum = #{chatRoomNum}  
								
								<if test="recentOutDate != null">
								
								and regdate > #{recentOutDate}
								
								</if>
								
								and chatContentNum > 0
</select>

### 변경후(일단은 돌아가게 만든 방법)

![image](https://user-images.githubusercontent.com/35983608/95761711-adee8200-0ce7-11eb-9e93-868a5c2d7772.png)
<select id="getChatContents" resultType="org.my.domain.ChatContentVO"> 
	 			
			select distinct content.chatContentNum 
																			, chat_writerId
																	    	, chat_writerNick
																	    	, chat_content
																	    	, content_type
																	    	, regdate
																	    	, readCount
																	    	, read.read_type
			
			from dk_chat_content content LEFT OUTER JOIN dk_chat_read read ON content.chatRoomNum = read.chatRoomNum 
			where content.chatRoomNum = #{chatRoomNum}
			
			<if test="recentOutDate != null">
										
				and content.regdate > #{recentOutDate}
			
			</if> 
			
			and content.chatContentNum > 0
			
			and read.chat_memberId = #{chat_memberId} order by content.chatContentNum asc
       
</select>

### 변경 후의 문제점 ( 데이터 조인 조회시 데이터 중복행의 발생 및 인덱스로 데이터 접근이 안되는 현상 )

1 ) 데이터 중복의 문제  > distinct 로 해결 > 다른 프로젝트에서도 똑같이 distinct로 해결했었으나 group by 와 비교해
장단점을 잘 살펴야 할 것 같다. 

일단 2가지의 공통점은 중복행을 제거 할 수 있다는점이다.

차이점은

distinct는 주로 UNIQUE(중복을 제거)한 컬럼이나 행을 조회하는 경우 사용

부하의 문제점(temp tablespace에 임시로 저장하고 작업하는 방식이라 시스템에 부하를 줄 수 있다고 한다)이 있으나 쿼리의 가독성이 좋고

![image](https://user-images.githubusercontent.com/35983608/95766572-68818300-0cee-11eb-934b-148a4cefc262.png)

group by 의 경우 보통 집계함수 (합계 평균 최대값) 를 사용하여 특정 그룹으로 구분 할 때는GROUP BY 절을 사용하나
쿼리의 가독성이 안좋아진다.( select절의 컬럼을 group by절에도 동일하게 명시를 해야하는 부담감 )
Oracle 10g R2 부터는 group by 사용 시 정렬(sort)이 기본으로 되지 않으므로 속도는 더 빨라 부하가 적음

그래서 결론은?무엇을 사용할 것인가? 쿼리의 가독성이 떨어져, 유지보수 하기 힘들다 싶은 정도가 되면
distinct를 사용하고 그렇지 않다면 성능을 우선순위로 잡을지

만약 도키 서비스의 채팅 빈도수를 예상하여 빈도가 낮다고 판단된다면 쿼리의 가독성을 살리고 성능을 포기할수도..
둘다 살리는 방법은 없는것일지?

2 ) 데이터 정렬의 문제 > 위처럼 order by로 일단 해결했으나, 이는 디비에서의 부하의 문제가 있다.(sort를 더 한다는점)
그래서 추가적인 sort없이 index로만 데이터를 조회해야하는데

아래와 같이 인덱스 흰트를 줄시 데이터 접근을 인덱스로 하지만, 왜 결과가 정렬이 안되어 있을지..?

- 쿼리
![image](https://user-images.githubusercontent.com/35983608/95767421-b3e86100-0cef-11eb-94af-ec85fdd7c751.png)

- 실행문 결과
![image](https://user-images.githubusercontent.com/35983608/95767320-8ac7d080-0cef-11eb-8431-56725d77e642.png)

- 정렬이 안되는 현상
![image](https://user-images.githubusercontent.com/35983608/95767464-c2cf1380-0cef-11eb-8c5a-2febf75f0990.png)

- 심지어 distinct를 사용하여 조회시 인덱스 접근 조차 하지못함

- 추측 하는 원인
조인을 할때도 인덱스를 활용해 정렬을 하려면 
NESTED-LOOPS JOIN (인덱스를 이용한 정렬 제거) 을 해야하는데

join
inner join
left outer join
right outer join
full outer join 등 어떤 조인을 하더라도

계속해서 
HASH JOIN
SORT MERGE JOIN

2가지만 계획 설명으로 잡힌다..

- 인덱스 흰트를 2가지 테이블에 주어도 정렬은 불가

**Comment by jongfeel** [comment]
1. 채팅 내용 테이터 조회 쿼리를 변경해야 하는 이유? 가 궁금하네요.
변경해서 되게 해놨다 까지는 좋은데, 왜 변경이 되어야 했는지에 대한 내용을 넣었으면 좋겠습니다.

2. distinct, group by의 목적이 중복을 제거하는데 목적있다고 했는데,
필요한 데이터가 무엇이기 때문에 distict로 해도 되는지, group by로 해도 되는지에 대한 이유가 필요합니다.
만약 내가 원하는 데이터가 두 방법으로 해도 문제가 없을 때
그때 가독성과 성능을 생각해 보는게 좋습니다.

3. INDEX_ASC hint는 table scan 할때의 최적화 작업을 위해 필요한 것입니다.
쿼리 결과에 대한 sort가 아닙니다.
https://docs.oracle.com/cd/B13789_01/server.101/b10752/hintsref.htm#5200

**Additional**

쿼리도 코드 처럼 조회하는 방법을 만들어서 결과를 얻는 행위이기 때문에
`HOW`에 엄청난 초점이 맞춰져 있습니다.

하지만 한발짝 물러서서 다시 생각해 보면 내가 얻어야 하는 `데이터`, 즉 `WHAT`이 중요함에도 불구하고
크게 중요하지 않을 수 있는 가독성, 성능에 집중이 되어 있습니다.
이 점을 다시 생각해 봤으면 좋겠습니다.

**Comment by ytw9699** [comment]
1. 변경을 해야하는 이유 : read_type컬럼이 값이 필요합니다. (https://github.com/ytw9699/Dokky/issues/240#issuecomment-703710813)
이 이슈에서 채팅 메시지 숫자 읽음의 여부를 판단하기 위해 read_type의 값이 필요합니다. 그래서 쿼리의 테이블의 추가 + 쿼리의 변경 (조인이 필요) 이 필요합니다.
![Uploading image.png…]()

**Comment by ytw9699** [comment]
how  : 어떻게 해야하는지에 대한 고민  > 몰라서 못한다는 생각 > 무언가 알아야지 할 수 있다는 생각
이 이슈에서 내가 쿼리를 짜는것을 잘 몰라서 문제 해결을 못하지 않나 의심을 했던것, 쿼리 짜는것은 찾아보면 언젠가 나옴
기술적인것들을 널려 있다.
( how 는 중요도가 상대적으로 낮다)

what :  how 에서 고민한 기술들을 사용을 해서 뭘 만들고 싶었는지?무엇을 만들고 싶었는지에 대한 생각
(이 이슈에서 이것이 what > https://github.com/ytw9699/Dokky/issues/247#issuecomment-707464095)
쿼리를 잘짜고 못짜고 보다도 (how ) 내가 원하는 데이터를 얻었냐 아니냐가 중요하다

why :  무엇을 만들어야 하는지 생각했다면 그러면 왜 이런것을 만들어야 하는지에 대한 생각

**Comment by ytw9699** [comment]
distinct 와 group by 의 사용 용도,목적,의도를 먼저 이해 해야 한다.

distinct는 정말로 중복을 없애서 하나로 만들어주는것이 사용 목적이고

group by  중복을 없애는것이 사용 목적이 아니라는것(중복을 없애주는것처럼 보이게 하는것)
  
보기에는 디비에서 가져온 결과가 같아보이나, 문법은 다르다

결국 요구하는 데이터를 잘, 정확하게 가져왔느냐가 쿼리를 만드는것의 중요한 의미

**Comment by ytw9699** [comment]
전체적으로 이 이슈에서는 오버엔지어링을 한것이다.

order by를 사용해서 정렬을 안하고 , 인덱스를 활용해서 정렬된 데이터를 가져올 필요까지가 없었던것

기준을 어디에 두냐가 중요할것인데, 내 프로젝트에서 채팅서비스가 엄청난 데이터를 가지고 있는것도 아니고
수많은 요청이 오는것도 아니기 때문

공부를 하다가 인덱스를 활용한 정렬에 대해 접한것이라, 공부의 용도로서 적합하나, 내 프로젝트에는 적합하지 않다.

**Comment by ytw9699** [comment]
INDEX_ASC hint는 table scan 할때의 최적화 작업을 위해 필요한 것
쿼리 결과에 대한 sort가 아닙니다.

흰트는 : 
힌트는 말 그대로 데이터베이스에 ’지금 내가 전달한 select문을 이렇게 실행해 주면 좋겠다는 것

INDEX_ASC hint는 정렬을 생략하는 방법

인덱스'라는 존재가 이미 정렬된 구조이므로 이를 이용해서 별도의 정렬 SORT 를 하지 않는 방법

pk는 중요한 의미 식별자 또는 인덱스의 의미

**Comment by ytw9699** [comment]
그래서 이 이슈를 겪고 정리한 내용으로 최종적으로 정리한 쿼리는 아래와 같아진다.

![image](https://user-images.githubusercontent.com/35983608/95999113-8971e180-0e70-11eb-8bd9-6cf3569b0bae.png)

**Comment by ytw9699** [comment]
위 쿼리는 다음 이슈에서 변경됨
https://github.com/ytw9699/Dokky/issues/254
추가적으로 distinct 도 필요가 없었다. 중복행 자체가 발생하지 않음
