### ISSUE TITLE
34th review meeting 

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#248]
### 1.  조인시에 인덱스를 활용한 데이터 정렬 (https://github.com/ytw9699/Dokky/issues/247)

조인시에도 분명 인덱스만 활용해서 정렬을 할 수 있는 것으로 알고 있는데
sql developer에서는 제가 만든 쿼리가 NESTED-LOOPS JOIN 으로 계획설명이 잡히지 않습니다.
이를 해결하지 못하는게 조인을 하는 쿼리에 대한 지식이 부족해서 라고 생각하는데 어떻게 생각하실지요?

### 2. group by와 distinct 의 선택의 문제( https://github.com/ytw9699/Dokky/issues/247 )

- 현재 도키 프로젝트에서 채팅의 사용 빈도수를 예측하기 어렵고
- 데이터를 조회하는 쿼리가 유지보수 하기 힘들정도의 큰 복잡성은 아니라고 생각이 되고
- 추후 성능의 문제가 생길것을 방지하여 

distinct보다는 sort를 하지않는 group by를 선택하려 하는데 어떻게 생각하실지요?

### 3. 웹소켓 설정의 문제 (https://github.com/ytw9699/Dokky/issues/246)

문제 해결은 되었습니다만, 이러한 문제가 발생하지 않다가 갑작스럽게 발생하는 이유가
어떠한 체크를 하지 않고 있었는데 , 이 기간이 지남으로 인해서 체크가 시작되었기 때문에 발생 했던거 같은데,
그래서 그 체크가 다시 동작하지 않게끔 기간을 off 시켜 버려서 해결이 된 것인지..
정확한 원인을 알아보는중인데 어찌 생각하실지요

**Comment by jongfeel** [comment]
1. https://github.com/ytw9699/Dokky/issues/247#issuecomment-707456666 가 있으니 참고하시면 됩니다.
쿼리에 대한 지식 보다는 그 지식을 오버해서 사용해 보려고 해서 문제인 것 같습니다.
쿼리의 결과로 얻고자 하는 데이터가 정확한지와 그 데이터가 사용자나 화면이 요구하는 대로의 데이터로 만들어 내는게 더 중요합니다. 쿼리 지식이 부족한건 중요하지 않습니다. 찾아서 해보면 되니까요.

2. 같은 issue이므로 코멘트 참고하시면 됩니다. 마찬가지의 이유입니다. 요구하는 데이터를 정확하게 가져올 수 있느냐로 distinct, group by를 고민하는 거지 복잡성, 성능으로 고민해야할 문제는 아닙니다.
두 문법의 차이가 내가 원하는 데이터를 정확하게 가져올 수 있는지 결과를 다시 리뷰해 보세요.
이정도 쿼리가 복잡성이 있어 보이지는 않고요
성능 문제를 논하려면 데이터가 100k 단위 정도는 되야 합니다.

3. https://github.com/ytw9699/Dokky/issues/246#issuecomment-707459629
제곧내입니다.

Additional

억지로 질문을 하는 것 같은 느낌인데 자연스럽게 대화하듯이 소통했으면 좋겠습니다.
리뷰할 내용을 꼭 미팅 당일날 만들어야 할 이유가 없기 때문에
계속해서 issue, pull request를 통해 절 assign 해 주시고 comment를 계속 주고 받으면
그게 훌륭한 리뷰가 됩니다.
