### ISSUE TITLE
35th review meeting - postponed

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#265]
최근 2 주일간 채팅 기능 구현에 상당히 많은 시간을 쓰신 것 같아요.

고민의 흔적도 보이고 진행 내용에 대해 정리도 잘 이루어지고 있는 것 같습니다.

저랑 논의할 내용은 따로 언급이 없으셔서 미팅은 다음주로 미루겠습니다.

그리고 논의할 내용이 없다 싶으면 미리 미팅 일정을 조정해 주세요.
제가 강제로 미루는 것 보다 미리 일정 조정을 하는게 좋습니다.

**Comment by ytw9699** [comment]
네 안그래도 리뷰 미팅 및 일정과 관련해 이슈를 쓰고 있었습니다.

이번에 여러 이슈들이 있었습니다만,

어떻게 어떻게 하다보니 해결은 대부분 한거같은데요.

아직 해결이 안된 이슈나  https://github.com/ytw9699/Dokky/issues/257

찝찝한 이슈들(제가 혼자서 나름의 기준을 세워가며 선택하여 해결)이 몇몇 있긴한데 조금 더 상황을 두고 볼까합니다.

그리고 이번 이슈들을 다시 돌아보았는데,

멘토님께선 말씀하신 

"무엇이 더 필요하고 알아야 하는지에 대한 내용"
"어떤게 필요하고 어떤게 부족한지 스스로 체크하고 얘기할 수 있는 긍정적인 부분"

은 살펴보지 못한거 같아요. 아직 좀 어려운것 같기도 하구요. 위에서 말씀하시는 뜻이

문제의 이슈 자체를 해결하는데 부족하고 필요한 내용이 아니라,

이슈는 해결했지만, 거기서 무엇이 더 필요하고 알아야 하는지에 대한 추가적인 내용을 말씀하시는걸까요?

**Comment by jongfeel** [comment]
어렵게 생각하지 마시고 얘기하고 싶은 부분이 있으면 절 넣어주시면 됩니다.

특별히 궁금하거나 논의할만한 내용이 없고, 문제를 잘 발견하고 해결한 것이라서 논의할 얘기가 없다면

그거대로 진행하셔도 상관 없어요.

구현하는데 집중해서 그런 것일 수도 있으니까요, 논의할 내용을 못만든걸 어려워하거나 잘못됐다고 생각 안하셔도 됩니다.

**Comment by ytw9699** [comment]
네 알겠습니다~!
