### ISSUE TITLE
채팅 리스트 조회 쿼리의 변경

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#266]
### 1. 하고자 하는것

채팅 리스트를 가져올때, 최신순으로 가져와야 한다.

이 최신순은 각 채팅방마다 마지막에 채팅내용을 입력한 시간이다.

그런데, 현재의 방법은 채팅 내용을 insert 할때마다 dk_chat_content 테이블에 시간(regdate컬럼에)을 입력

하면서 dk_chat_room 테이블에도 (input_content_date컬럼에 ) 시간을 입력을 하고있다.

즉 채팅내용 테이블에도 시간을 입력하면서, 채팅룸테이블에도 시간을 2번입력하는것인데, 

처음 이렇게 2번 입력 한 이유가 채팅리스트를 불러오는 쿼리가 복잡해질것이라 생각했기 때문이었다.

그런데 다시 생각해보니, 채팅리스트를 불러오는 사용량이 많을지, 채팅내용을 입력하는 사용량이 많을지중에, 후자이다.

보통 채팅내용입력 횟수가 리스트 불러오는 횟수보다 많을것이기 때문에, 채팅내용을 입력할때, 시간을 2번 insert 해주는게 비효율적이라 생각했다.

그래서 채팅리스트 조회를 위해 특정 chatRoomNum을 가져오는 쿼리를 변경 해보려고 한다.

이때 조회한 결과, 주의할점이 중복행이 발생하면 안되는데 chatRoomNum컬럼값이 중복된다면 중복으로 보자는 것이다.
다른 컬럼은 중복이 안되더라도 기준은 chatRoomNum이다.

### 2. 원래의 쿼리()

채팅내용을 입력할때 채팅룸 테이블에서 날짜 업데이트
![image](https://user-images.githubusercontent.com/35983608/98122542-14844b80-1ef4-11eb-8ee5-cd2f18e7ab21.png)

채팅 리스트를 불러오기전 선행되어야 하는 쿼리(업데이트된 날짜로 정렬)
![image](https://user-images.githubusercontent.com/35983608/98010524-24d7f000-1e3a-11eb-8fb7-6871cbe4479c.png)

### 3. 변경해본 쿼리

채팅룸 테이블에 날짜 업데이트를 없애버리고

채팅 리스트 불러오기전 선행되어야 하는 쿼리만 변경

`
WITH mytable AS ( select chatRoomNum, chat_type, chat_title, regdate from (select room.chatRoomNum, room.chat_type, room.chat_title, content.regdate
from dk_chat_room room inner join dk_chat_member member on room.chatRoomNum = member.chatRoomNum inner join dk_chat_content content on member.chatRoomNum = content.chatRoomNum 
				where member.chat_memberId = 'admin' and member.present_position = 0 order by content.regdate desc ) )
                select chatRoomNum, chat_type, chat_title, regdate from mytable where rowid in (select max(rowid)from mytable group by mytable.chatRoomNum)
`

### 4. 변경을 하면서 알게된점

distinct 는 중복행을 제거할 수 있지만, 모든 컬럼이 중복이지 않으면 제거 해주지 않는다.

특정한 a컬럼이 중복되고 있을때, b컬럼이 중복되지않는다면, a컬럼의 중복만을 체크해 제거 하고 싶지만 불가하다.

https://blog.naver.com/PostView.nhn?blogId=deeperain&logNo=221448041099

그래서 rowid를 사용해야 한다.

### 5. 문제점

변경한 쿼리가 돌지않는다.

ORA-01445: 키 보존 테이블이 없는 조인 뷰에서 ROWID를 선택할 수 없음
01445. 00000 -  "cannot select ROWID from, or sample, a join view without a key-preserved table"

distinct로 특정 컬럼을 기준으로 중복을 제거하려 했지만, 이점이 불가해 rowid를 쓰려한건데

rowid를 조인과 함께 쓰려니 계속 막혀버린다.

**Comment by ytw9699** [comment]
참조 사이트

- 서브 쿼리 with 구문 : https://mine-it-record.tistory.com/178
https://sites.google.com/site/smcgbu/home/gongbu-iyagi/withgumunseobeukwolileulnaema-eumdaelo
- where in : https://inforyou.tistory.com/28
- distinct 가 아닌 rowid와 group by를 활용한 특정 컬럼 기준 중복제거(특정 컬럼의 중복만 제외시키고 나머지 컬럼들은 그대로 불러와야 할 경우)
https://m.blog.naver.com/PostView.nhn?blogId=csaiur&logNo=10149347206&proxyReferer=https:%2F%2Fwww.google.com%2F
https://blog.naver.com/PostView.nhn?blogId=deeperain&logNo=221448041099

**Comment by ytw9699** [comment]
### 5. 이어서 문제점 

서브쿼리의 별칭 값으로 가져온 테이블에서는 rowid가 조회가 안되는것 같다..

그리고 추가적으로 이상한것은
select chatRoomNum, chat_content, regdate from dk_chat_content where rowid in (select max(rowid) from dk_chat_content group by chatRoomNum)

이렇게 간단한 조회만 할경우 조회가 가능은 하지만,
max(rowid) 로 최대값을 주면 최신순으로 조회가 되는걸로 아는데 안되고 있다 이유를 알수 없음. min도 불가

그래서 아래와 같이 regdate로 조회를 하니 최신순으로 가능했다.
select chatRoomNum, chat_content, regdate from dk_chat_content where regdate in (select max(regdate) from dk_chat_content group by chatRoomNum)

**Comment by ytw9699** [comment]
### 6 .최종적으로 변경 전후 쿼리

![image](https://user-images.githubusercontent.com/35983608/98118441-8fe2fe80-1eee-11eb-9769-4578bd36c583.png)

**Comment by ytw9699** [comment]
### 7. 원하는 결과

각 방마다 마지막에 보낸 채팅내용의 최신순으로 채팅 리스트가 나열된다.

![image](https://user-images.githubusercontent.com/35983608/98120393-3c25e480-1ef1-11eb-868e-41198e1393e5.png)

이렇게 조회가 되면 굳이 채팅 내용을 입력할때마다

dk_chat_room 테이블의 input_content_date 컬럼을 입력할 필요가 없어지게 되었다. 불필요 컬럼 삭제도 가능

input_content_date date default sysdate, --(채팅내용이 입력되면 날짜를 업데이트)

**Comment by ytw9699** [comment]
https://github.com/ytw9699/Dokky/issues/266#issuecomment-721736798

결국 rowid로는 정렬이 불가

regdate 말고 chatContentNum과 같이 다른 정렬이 가능한 컬럼으로도 가능

![image](https://user-images.githubusercontent.com/35983608/98256481-ef5e0e80-1fc1-11eb-88ac-f3565af601ea.png)

**Comment by ytw9699** [comment]
이 이슈가 아무래도 찜찜하네요.

변경전과 후를 비교했을때 

크게 비효율이 없어졌다고 하기도 애매한 것 같다는 생각이 드네요..

dk_chat_room 테이블에 한번 더 insert하는 것을 없애고, dk_chat_room  테이블에 input_content_date 컬럼을 삭제하는 대신에

불러오는 쿼리는 간단한것에서 쪼금 더 복잡(조인 3개)해졌구요.

https://github.com/ytw9699/Dokky/blob/29d8daf2d19f3e627f30fe87b01d280fc5e7607d/dokky/src/main/java/org/my/service/ChatServiceImpl.java#L246

이 변경과정에서  distinct , rowid와 group by등등의 쿼리 사용법을 학습했다는데 의미는 있었지만요

변경 전후에 대해서 어찌 생각하실지요~?

결국 제가 한것은 데이터 중복을 없애는 정규화를 한것 같은데, 정규화와 비정규화 모두 장단점이 있다보니요

https://owlyr.tistory.com/20

**Comment by jongfeel** [comment]
내가 수행한 작업이 어떤 의미를 가지는지를 잘 살펴보시면 됩니다.

1.
효율적이냐 비효율적이냐의 기준을 어디에 두고 싶은지 정하는게 우선입니다.

- dk_chat_content.regdate, dk_chat_room.input_content_date 둘 다 시간을 입력하는게 비효율적
- 그래서 chatContentNum 순서로 쿼리를 변경했을 때 dk_chat_room.input_content_date를 입력 안해 되므로 변경 전 쿼리보다 복잡성이 해결되었는지 확인

시작은 table 두 군데에 시간을 입력하는게 비효율적이라고 했는데
시간을 입력 안해도 가져올 수 있으면 효율적으로 된거라고 보면 됩니다.

2.
쿼리의 복잡성은 리팩토링을 거쳐서 해결해 볼 수 있을 수도 있습니다.
단, 쿼리를 아무리 잘 만들려고 해도 복잡성이라는 건 주관적이므로, 
쿼리 만드는 경험 부족일 수도 있고요 (문법 활용 능력 포함)
혹은
테이블 설계가 잘못되서 쿼리가 복잡해지는 경우도 있습니다.

3.
`효율적인 방법`의 정의를 다시 잘 생각하고 작업을 진행해야 합니다.

- 쿼리의 복잡성을 단순함으로 바꾸는게 이 효율적인 건지
- 쿼리 작업 수행 횟수를 2회 -> 1회로 줄이는게 효율적인 건지
- 다른 쿼리 문법 적용을 통해 전에도 잘 되던 건데 더 잘 되게 만든게 효율적인 건지

문제 정의를 내가 잘 했으면, 결과 역시 문제 정의를 해결하기 위한 방법이었는지를 다시 생각해 보시면 됩니다.

**Comment by jongfeel** [comment]
이번 이슈의 쿼리문에 대한 전 후 변경 과정에 대한 리뷰를 함께 해 보면 좋을 것 같네요.

**Comment by ytw9699** [comment]
만약 그 효율성의 기준을 디비가 도는 작업의 속도라고 잡는다면,

변경 전과 후에 실행되어야 하는 쿼리들의 실행 속도를 더해서 테스트 해보면 되는것일까요?

그 결과 속도가 빨라졌다면, 효율적으로 바꿨다라고 객관적으로 볼 수 있을까요

**Comment by jongfeel** [comment]
네 얘기하신 대로 하면 맞습니다.

그런데 제가 봤을 때는 그렇게 유의미한 실행 속도 향상이 있어 보이진 않을 것 같지는 않습니다.

만약 실행속도에 큰 차이가 없다면 (100ms 이내의 오차 범위)

오히려 가독성 있는 쿼리문을 만드는게 더 좋은 방향의 효율(?)성을 높이는 작업이라고 생각합니다.

**Comment by ytw9699** [comment]
아... 감사합니다!

**Comment by jongfeel** [comment]
그래서 파생되는 문제점에 대해서는 새로운 이슈로 만들고 연결된 이슈로 관리하면 좋습니다.

**Comment by ytw9699** [comment]
위처럼 하나의 이슈에다가 문제를 여러개 써두면, 한꺼번에 여러개를 해결해야하는 복잡성이 커진다.

그러다 보니 문제 해결이 복잡하고 헷갈리고, 시간이 더 걸렸던 것 같다.

문제가 여러개면 이슈도 여러개 만들면 된다. 한 이슈로 부터 파생된 다른 이슈들은

링크로 연결해보자. 그렇게 관리하는게 좋다라는것

- 쿼리의 복잡성 > 또 다른 이슈
- 조인을 함으로써 성능 저하 > 또 다른 이슈

**Comment by ytw9699** [comment]
여기서 말하는 가독성있는 쿼리문은 : 나중에 수정 할 수있게 이름 같은걸 잘 만들어놨는지등을 체크

**Comment by ytw9699** [comment]
결론적으로 두번 인서트하나, 조인을 해서 가져오나 성능상에서 큰 차이는 없을것 같다는 결론
두번 인서트 함으로써 쿼리문의 간단하게 만들어 쿼리 복잡성을 낮추는게 효율적이라 볼수도 있고
그건 어떻게 보느냐에 따라 달라질듯 하다.

**Comment by ytw9699** [comment]
추가적으로

정규화는 설계단계에서 하는것

정규화랑 쿼리랑은 상관없음!

그러면 만약 정규화를 설계단계에서 이미 해둬서  
내가 insert 해야하는 데이터가2개일때? 한번 insert만으로 해결할수 없는건가?

db 시스템에 있는 기능들을 사용하면됨

트리거,프로시져로 가능

설계단계에서는 트리거, 프로시저를 써야한다라고만 명시
어떤 테이블에 데이터가 입력이될때, 다른 테이블에 트리거,프로시저를 써서 인서트가 되어야 한다 라는 설계문서

프로시져를 많이 만드는 사람일수록 경험이 많다고 볼수있고
쿼리문이 비지니스상에 코드로있는게 이미 초보

**Comment by ytw9699** [comment]
추가적으로 디비를 관리하는 것들을 생각해보면

디비설계하는 사람의 관점에서는 프로시저, 트리거를 쓰자고 할 수 있지만
백엔드 개발자 관점에서는 orm(데이터베이스 관리 패키지, 함수호출을 하면서 쿼리문이 되는것처럼 하게 만드는것
실제로는 쿼리가 도는것임) 같은것을 써서 디비를 관리할수 있다.

**Comment by ytw9699** [comment]
최종적으로 이 문제를 해결하기 위해 선택한 방향은

https://github.com/ytw9699/Dokky/issues/266#issuecomment-722428169

인서트를 딱 한번만 하게 만들고, 가져오는 쿼리문을 조금 복잡하게 만들어 놨는데, 성능은 테스트시 별차이 없는것 같다.

여러 곳에 인서트를 두번이나 하는게 관리적인면에서 분산되는걸 좋아하지 않았던 것도 있다.

추후 개선이 필요하다면  https://github.com/ytw9699/Dokky/issues/266#issuecomment-727168804 참고하자
