### ISSUE TITLE
프론트와 백엔드에서 관리하는 값의 안정성 향상 방법

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#273]
### 문제점

이 이슈로부터 https://github.com/ytw9699/Dokky/issues/258 문제가 파생되었다.

채팅방 화면에서의 문제점인데,

https://github.com/ytw9699/Dokky/blob/6d0b3f51bda804523fb47a9789803254ea14e008/dokky/src/main/webapp/WEB-INF/views/chat/chatRoom.jsp#L253

프론트에서 관리하는 headcount의 값과

디비에서 관리하는 headcount의 값의 일치 및 안정성에 대해 생각해 볼 문제가 있다.

### 전체 흐름은

- 처음 채팅방 화면을 요청(입장)할때, 디비로부터 저장된 해당 채팅방의 인원수를 가져옴. 1:1채팅방이라 2를 가져왔다고 가정하자.
- 만약 방에서  한명이 나간다면 디비에서 headcount값을 -1 해주고, 따로 채팅방 화면에서도 -1을 해준다.
https://github.com/ytw9699/Dokky/blob/6d0b3f51bda804523fb47a9789803254ea14e008/dokky/src/main/webapp/WEB-INF/views/chat/chatRoom.jsp#L480

그런데 이런 흐름에서의 headcount값의 유지에 안정성이 떨어진다고 생각이든다. 

디비의 실제 headcount값과 화면에서의 headcount값이 차이가 생길 확률이 있을것 같다.

그러한 경우가 방에서 한명이 나가면서 디비의 값을 -1해줬는데, 
채팅 상대방의 화면에서 어떤 오류들?로 인해서 headcount값이 업데이트가 안된다면 차이가 생기는 것이다.

그래서 이에 대해 한단계 더 안전한 관리장치가 필요할 것 같다.

### 어떤 오류들이라면

- 1 ) 웹소켓이 끊기는 경우
- 2 ) 인터넷이 끊기는 경우
- 3 ) 알수 없는 기타의 경우, 응답이 제대로 안가는 경우

### 백엔드 측면 해결법
- 기존의 방법 : 현재는 채팅메시지를 보낼때, 보내는 사용자의 화면단에서 headcount값을 받아서 이를 곧바로 디비에 입력하고 있는데,
https://github.com/ytw9699/Dokky/blob/6d0b3f51bda804523fb47a9789803254ea14e008/dokky/src/main/webapp/WEB-INF/views/chat/chatRoom.jsp#L666

-  변경 방법 : 이러한 방식이 아니라 채팅메시지를 보낼때 화면단에서 headcount의 값 없이 요청하고,
아래 웹소켓 핸들러에서 다시 디비에 접근해 해당 채팅방의 headcount값을 가져와서 처리하는 방향
https://github.com/ytw9699/Dokky/blob/6d0b3f51bda804523fb47a9789803254ea14e008/dokky/src/main/java/org/my/handler/chatWebsocketHandler.java#L126
 chatContentVO.setReadCount(디비로부터 headcount값 가져오기); 

### 프론트 측면 해결법

- 기존의 방법 : 채팅메시지가 웹소켓을 통해 한번이 오면, 화면단에서 headcount의 값을 -1빼주는 방식

- 변경 방법 : 기존에 프론트에서 관리하던 방식을 유지하지않고, 오류가 발생하던 말던
headcount의 값을 rest api로 디비에서 가져와서 업데이트 해주는 방식

**Comment by ytw9699** [comment]
현재 화면단 headcount의 값이 전역변수로서 사용되기 때문에 아래 이슈와 연장선에 있어보인다.
https://github.com/ytw9699/Dokky/issues/259

**Comment by ytw9699** [comment]
@jongfeel 여기서도 비슷한 문제입니다.
프론트 측면해결법으로 해결하거나 아예 프론트에서 headcount값을 유지안하고
서버쪽에서 필요할때마다 headcount값을 체크하는 방식이 좋을거 같다는 생각인데 어떻게 생각하실지요

**Comment by jongfeel** [comment]
예상 하신 오류들로 인해 프론트엔드에서 처리하기에는 어렵기도 하고 보완해야 할 부분이 많습니다.
- 물리적 네트워크 끊김
- 소프트웨어적 웹소켓 끊김
- 어떤 이유에서든 응답이 없어서 끊김(?)으로 인식하는 경우

백엔드에서 관리하는 방식으로 해보면 좋을 것 같습니다.

**Comment by ytw9699** [comment]
headcount의 관리를 백엔드에서만 처리하는 관련 로직들
https://github.com/ytw9699/Dokky/commit/6de69b3087b415abd331fbebb976d2268a441851
