### ISSUE TITLE
채팅 웹소켓 세션관리 방법의 변경

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#296]
연결 이슈: https://github.com/ytw9699/Dokky/issues/294#issuecomment-731767108

### 1. 프론트에서 데이터 받기

![image](https://user-images.githubusercontent.com/35983608/99951180-02921c00-2dc1-11eb-8b0b-ffafb3069b01.png)

일단 afterConnectionClosed(WebSocketSession session, CloseStatus status) 메소드에서

화면단으로부터 데이터를 받아오는건 불가한것 같다. 찾아보아도 그러한 예시가 안보임
그렇다고 status인자에서도 데이터 받는것은 불가.

INFO : org.my.handler.chatWebsocketHandler - chatWebsocketHandler afterConnectionClosed:StandardWebSocketSession[id=9, uri=/chatWebsocketHandler]:CloseStatus[code=1000, reason=null]

### 2. 해결방법의 방향
받아온 세션 객체 만을 활용해 해결해야 하는듯 싶다.

**Comment by ytw9699** [comment]
### 3. 확인한 해결 방법중 하나
websoketSession 객체에 http 세션 객체가 담겨있다.
채팅방에 접속할때 http세션에다가 채팅방 번호를 미리 넣어두면
웹소켓 핸들러에서 채팅방 번호를 받아올 수 있다.

**Comment by ytw9699** [comment]
### 4. 다시 생겨난 문제점

문제는 사용자가 채팅방을 여러개 열어둘 수 있다는것이다.

그러면 세션에도 여러개의 채팅방 번호가 저장이 되어 있어야 한다.

그리고 비정상적으로 연결이 끊겼을때 그 세션에 해당하는 채팅방 번호를 탐색해서 찾아와야 한다.

**Comment by ytw9699** [comment]
### 5. 다른 방법으로 전환

세션에다가 여러개의 채팅방 번호를 저장해두고 이를 다시 불러오는 과정을 거치지 않고

그냥 바로.. chatWebsocketHandler핸들러 안에다가 키와 값으로 저장해두는 방식으로 관리를 해보는게 좋을것 같다.

이게 웹소켓 객체를 처음 생성할때, 화면단으로부터 데이터를 못받아오기 때문에 불가능하다고 처음에 생각했는데, 

그것은 맞다. 하지만 생성후 메시지를 하나 의무적으로 보내고 받아오면 된다.

키는 웹소켓 세션의 아이디, 값은 채팅방 번호로 저장해두고 관리한다.

**Comment by ytw9699** [comment]
### 6. 변경한 코드

https://github.com/ytw9699/Dokky/commit/48a0e83235f859aa476ce838afe4c4c68c51dec5

**Comment by ytw9699** [comment]
이렇게 코드를 변경한 이유가

기존에는 비정상적으로 닫혀버리는 웹소켓 객체에 대한 관리가 없었던 상태이다.

즉 ChatRoom객체의 맵안에 닫혀버린 웹소켓 객체가 저장이 되어있는 상태.

그래서 해당하는 채팅방의 사용자들에게 메시지를 보낼때, 웹소켓 객체가 닫힌건지 살은건지 판단해서 보내는 형태

https://github.com/ytw9699/Dokky/blob/48a0e83235f859aa476ce838afe4c4c68c51dec5/dokky/src/main/java/org/my/domain/ChatRoom.java#L119-L138

하지만 변경을 하고나서부터는

위 코드가 사라지고, 닫혔는지 아닌지 판단이 필요없이 바로바로 메시지를 보낼수 있음

https://github.com/ytw9699/Dokky/blob/48a0e83235f859aa476ce838afe4c4c68c51dec5/dokky/src/main/java/org/my/domain/ChatRoom.java#L113-L117

이를 위해서 chatWebsocketHandler에서 키와 값으로 웹소켓 세션의 아이디, 값은 채팅방 번호로 저장해두고 관리가 필요

https://github.com/ytw9699/Dokky/blob/48a0e83235f859aa476ce838afe4c4c68c51dec5/dokky/src/main/java/org/my/handler/chatWebsocketHandler.java#L31

**Comment by ytw9699** [comment]
그런데 이렇게 변경을 하나 안하나, 비정상적으로 웹소켓이 닫혔을때 돌아가는 것은 가능하다는 것.

그럼 뭘 위해서?

**Comment by jongfeel** [comment]
session 상태 관리가 확실하다면 메시지를 보낼 때 마다 체크해야 하는 건 안해도 될 수 있습니다.

구현 방식에 대해 크게 의견이 없긴 하지만
태원님이 생각하는 문제점 혹은 걱정거리가 어디에서 오는 건지 얘기를 한번 들어볼 필요는 있을 듯 하네요.

리뷰 미팅 시간에 한번 얘기해 보면 좋을 것 같습니다.

**Comment by ytw9699** [comment]
채팅 웹소켓에서의 오류가 발생 > 
그것의 원인을 찾고자 함 >
원인을 잘 못찾아, 이 이슈처럼 세션에 대한 확실한 관리 대비책을 만들어둠 >
그 외 문제가 될 만한것들을 모조리 수정 https://github.com/ytw9699/Dokky/issues/294#issuecomment-736375353> 
그 이후로 현재까지 문제 발생은 안해서 다행이지만 찝찝함에 다시 원인을 찾고자함 >
그 원인이 비정상적인 웹소켓의 끊김현상인지 아직 잘 모르겠음 >
이클립스 도구의 저장버튼을 눌러 톰캣이 재시작 된것이 원인인지
