### ISSUE TITLE
commonWebsocket 세션객체의 관리방법의 변경

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#303]
### 1. 변경 이유

- 중복 로그인이 가능하다고 가정하기 때문에
- 그리고 중복 로그인 뿐만 아니라 , 중복 새창 마다 웹소켓을 통해 알림,쪽지등의 신호를 실시간으로 받아야 하기 때문

그래서 웹소켓 세션 또한 새창마다 각각, 중복으로 저장이 되어야 한다.

그런데 현재는 맵에다가,  키는 유저의 아이디로 값은 세션으로 저장이 되고있다.
맵의 키는 중복을 허용하지 않기 때문에
https://github.com/ytw9699/Dokky/blob/09edc7346a9d5d772b87e0c1a7911f5dbe33f954/dokky/src/main/java/org/my/handler/commonWebsocketHandler.java#L16-L25
이를 맵에서 >다른 자료구조로 변경해야 한다.

### 2. 어떤것으로 변경?
키와 값이 모두 중복으로 저장이 되는 자료구조가 필요한데..

키와 값이 모두 중복으로 저장되는것은 잘 안보이고

맵안에다가 맵을 넣는 방향으로 가야할 것 같다.

**Comment by ytw9699** [comment]
### 3. 맵안에 맵을 넣는 자료구조 선택 이유

**Comment by ytw9699** [comment]
코드의 변경
https://github.com/ytw9699/Dokky/commit/d866775b63a9834f32ebe5b26b169d0ede6c19a6


HashMap은 해시 알고리즘을 쓰고, 결국 배열을 기반으로 한 자료구조 이기 때문에
검색속도 O(1)
추가 삭제 O(n)

TreeMap은 키와 값을 한 쌍으로 하는 데이터를 이진 검색 트리의 형태로 저장, 
검색속도 O(log n)
데이터 추가,삭제 O(log n)

LinkedHashMap은 해시알고리즘 + 양방향 연결리스트 구조로 순서를 보장
검색속도  O(1)
데이터 추가,삭제 O(1)

지금 코드가 변경이 이루어지고 나서
예상되는 동작은 검색보다는 추가삭제가 확실히 많을것 같다.
왜냐하면 페이지 이동시마다 웹소켓객체를 만들면서 
웹소켓 세션이 끊기고 다시 생성되기 때문에 이때, 추가 삭제가 계속해서 이루어짐
LinkedHashMap의 경우 검색이나 추가,삭제 모두 상수시간의 시간복잡도를 보임

메모리는 고려를 안한다면 현재 상태에서 LinkedHashMap이 가장 적합할것 같은데,

**Comment by ytw9699** [comment]
https://github.com/ytw9699/Dokky/issues/292#issuecomment-731590958

**Comment by ytw9699** [comment]
정리하자면 

https://github.com/ytw9699/Dokky/blob/d866775b63a9834f32ebe5b26b169d0ede6c19a6/dokky/src/main/java/org/my/handler/commonWebsocketHandler.java#L17

- 이 맵에서 데이터 추가 삭제가 훨씬 많을 것이다.
- 데이터 검색은 적을 것이다.

그러면 LinkedHashMap이 검색도 빠르고, 추가삭제도 빠르기 때문에 적합하다

하지만 LinkedHashMap은 메모리 사용량이 많아질것이다..

사용자가 많아진다면 LinkedHashMap을 쓰면.. 메모리 사용량이 많아질것이다. 사용자만큼 객체가 생성되기 때문

그러면 현재 기준을 내 현재의 프로젝트로 잡아본다면..? 사용자가 별로 없어서 메모리 사용량에 대해
고민하는게 무의미할것도 같다. 

그러면 LinkedHashMap이 맞다.

그런데 사용자가 없을 것이라고 목표하고 만드는 사이트인가?

현재 이 프로젝트는 커뮤니티이고 > 커뮤니티는 사용자들이 많아짐을 기대하는것인데

결국, 사용자가 많아질것이라면 메모리 사용량도 고려를 해야하는게 의미가 있을지..?

이것 자체를 모두 고민하는게.. 또 오버 엔지니어링을 하는것 아닌지..?

**Comment by ytw9699** [comment]
@jongfeel assignees를 요청 드립니다.

**Comment by jongfeel** [comment]
자료구조는 LinkedHashMap을 써도 괜찮을 것 같습니다.

그런데 질문이 두 개 있습니다.
- 메모리 사용량이나 성능 문제 말고 LinkedHashMap을 쓴다는 건 순서가 중요하기 때문에 쓰는 건데, 구현하려는 로직에서 순서가 중요하기 때문에 쓴 코드가 있나요?
- 유저 아이디 별로 세션들 값을 저장하는 단순한 map의 형태는 안되는 걸까요?

``` java
Map<String, ArrayList<WebSocketSession>> userSessionsMap = new LinkedHashMap<>();
```

제가 얘기하는 `Over engineering`은 필요에 맞게 쓴게 아니라 필요하지도 않은데 정말 오버해서 구현한 걸 문제삼는 것입니다. 오버 엔지니어링이 결코 성능 하락, 메모리 낭비가 주된 주제가 아니라는 뜻이기도 합니다.

**Comment by ytw9699** [comment]
ArrayList<WebSocketSession>안에 세션들값을 저장하는것이 속도면에서 안좋을것 이라고 생각을 했습니다.

ArrayList 의 경우에는 내부적으로 배열을 쓰는지라, 검색속도와, 데이터 추가는 상수시간에 가능하지만
삭제의 경우, 배열의 구조가 변경되므로 느리다고 알고 있습니다.

그런데 자세히 생각해보니, userSessionsMap의 경우 회원들의 수만큼 데이터가 쌓이기 때문에 삭제 속도를 신경써줘야 하지만

ArrayList<WebSocketSession> 의 경우는 큰 데이터가 쌓이지 않을거 같네요. 중복된 창이 많아봐야 얼마 안될것 같기 때문에,

삭제하는데 큰 시간이 소요되는게 아닐거 같아서요.

그래서 결론적으로 

Map<String, ArrayList<WebSocketSession>> userSessionsMap = new LinkedHashMap<>();

이렇게 쓰는것도 가능할 것 같습니다.

**Comment by ytw9699** [comment]
구현하려는 로직에서 순서가 중요하기 때문에 쓴 코드는 없습니다. 키에 해당하는 값만 가져오면 되기 때문입니다.

LinkedHashMap이 연결리스트를 내부적으로 사용하기 때문에 순서유지가 되고 그러한 성격을 가진 자료구조인것 같은데

현재 상황에서 중요하다고 생각하는 아래 사항들을 만족시킬 다른 대안을 못찾았습니다.

- 키-값 쌍이 필요하다 
- 추가,삭제의 속도가 검색속도 보다 중요하다
- 메모리 사용량이 적었으면 한다.

**Comment by ytw9699** [comment]
hashmap이냐 LinkedHashMap이냐도 다시 찾아봐야 할 것 같아요.

https://github.com/ytw9699/Dokky/issues/305

**Comment by jongfeel** [comment]
저는 아래 내용을 상당히 주의해야 한다고 생각합니다.

> 구현하려는 로직에서 순서가 중요하기 때문에 쓴 코드는 없습니다

LinkedHashMap이 왜 필요하나요? 라고 물어보면
저는 당연히 순서가 중요한 데이터가 있고 그 데이터를 찾기 위해 수월한 자료구조를 선택했다는 답이 맞는 답이라고 보거든요.

속도, 메모리 이런거 위주로 하려면
ArrayList는 평생 쓰지도 못할 자료구조이고
Stack, Queue 역시 마찬가지겠죠.

그럼에도 불구하고 ArrayList, Stack, Queue를 쓰는 이유가 있기 때문에 쓰는 거라고 생각하는게 맞다고 봅니다.
그게 메모리 사용량, 성능 이런 문제가 아니고요.

오래만에 좋은 논의 주제를 찾은 것 같아 좋은 것 같습니다.

**Comment by ytw9699** [comment]
자료구조의 선택을 할때 생각해볼점

1차적 : 자료구조의 선택의 생각의 방향을 내가처리하려는 로직과 자료구조의 성격과 특징이 일치하는지에 중점을 두는게 1차적
각각의 자료구조는 그에 맞는 상황에 적합하게 써주는것이 중요하다.
2차적 : 추가적으로 필요하다면 성능과 메모리도 생각해보기

현재 상황에서 키-값 쌍이 필요하고, 순서대로 탐색을 하는 경우는 없으므로, LinkedHashMap보다는 HashMap이라고 볼 수 있을것이고, 추가적으로 성능 퍼포먼스도 HashMap 과 LinkedHashMap이 큰 차이가 없음을 확인 했기에 최종적으로 HashMap을 선택하기로 했다.

코드의 변경

- 자료구조의 변경
- https://github.com/ytw9699/Dokky/issues/303#issuecomment-735788790

**Comment by ytw9699** [comment]
코드의 변경과 관계없이 파생된 문제가 발생
