### ISSUE TITLE
37th review meeting - postponed 

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#314]
멘토님 이번에 대체로 구현에 집중하여 리뷰할것이 없네요.

1주 더 연장하면 좋을거 같습니다.

**Comment by jongfeel** [comment]
네 알겠습니다.

**Comment by ytw9699** [comment]
멘토님 이번주도 저번주와 상황이 같네요 ~ 1주 더 연장하면 좋을거 같습니다.
