### ISSUE TITLE
채팅룸 프론트에서 관리하는 변수값의 문제

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#319]
### 1. 연관된 이슈: https://github.com/ytw9699/Dokky/issues/273, https://github.com/ytw9699/Dokky/issues/259, 
연관된 코드리뷰 : https://github.com/ytw9699/Dokky/pull/239

### 2. 문제 및 고민점

https://github.com/ytw9699/Dokky/issues/321 과 똑같은 문제

#### 동작 전체흐름
1. 1:1채팅방에서 상대방이 다른 인원을 초대한다.
2. 그러면 채팅방에 있는 모든이들에게 멀티채팅방으로 타입이 변환이 되어야 한다.

현재는 전역변수를 쓰지않고 컨트롤러에서 요청 페이지로 넘겨준 값 "${chat_type}"을 가져오고 있는데
이는 한번 응답을 받고나서는 변하지않는다. 

그래서 chat_type의 값을 전역변수로 선언하고 상대방이 초대를 했을때  나의 채팅방으로 서버에서 푸시가오고 
이때 프론트에서 전역변수의  값의 타입을 멀티로 변환시킬것인지?

아니면 상대방이 초대하더라도 프론트에서 chat_type의 값의 변화없이 가만히있다가
chat_type의 값을 필요로 하는 곳이 생길때 rest api로 chat_type의 값을 디비에서 가져올것인지

#### 불안점
웹소켓 통신을 할때에 혹시모르게 발생할 버그들로 인해서 화면단의 chat_type의 값이 실시간으로 업데이트가 되지않을 확률도 있을것 같다는 불안감.. 이것때문에 확실하게 chat_type값이 필요할때마다 디비에 접근해서 값을 가져오는 방향이 맞을지
하지만 만약 이러한 불안점을 해결했다고 해도 값이 필요할때마다 디비로부터 값을 가져올것인지, 아니면 전역변수에 저장을 해둘것인지에 대한 고민

### 3. 코드 위치 : chat_type변수

https://github.com/ytw9699/Dokky/blob/623c785c916715b445816b9662531f1d0ee6b8b2/dokky/src/main/webapp/WEB-INF/views/chat/chatRoom.jsp#L594

**Comment by ytw9699** [comment]
### 전체 흐름

1. 1:1채팅방에서 상대방이 다른 인원을 초대한다.
2. 그러면 채팅방에 있는 모든이들에게 멀티채팅방으로 타입이 변환이 되어야 한다.

현재는 전역변수를 쓰지않고 컨트롤러에서 요청 페이지로 넘겨준 값 "${chat_type}"을 가져오고 있는데
이는 한번 응답을 받고나서는 변하지않는다. 

그래서 chat_type의 값을 전역변수로 선언하고 상대방이 초대를 했을때  나의 채팅방으로 서버에서 푸시가오고 
이때 프론트에서 전역변수의  값의 타입을 멀티로 변환시킬것인지?

아니면 상대방이 초대하더라도 프론트에서 chat_type의 값의 변화없이 가만히있다가
chat_type의 값을 필요로 하는 곳이 생길때 rest api로 chat_type의 값을 디비에서 가져올것인지

### 불안점
웹소켓 통신을 할때에 어떤 버그들로 인해서 화면단의 chat_type의 값이 실시간으로 업데이트가 되지않을 확률도 있을것 같다는 불안감..
이것때문에 확실하게 chat_type값이 필요할때마다 디비에 접근해서 값을 가져오는 방향이 맞을지

**Comment by ytw9699** [comment]
첫번째 방법대로 코드의 변경
- chat_type와 chatMembersArray 값을 전역변수로 선언하고, 초대 메시지가 오면 이곳에 업데이트 시켜주기

**Comment by ytw9699** [comment]
두번째 방법대로 코드의 변경
chat_type의 값과 chatMembersArray값을  필요로 하는 곳이 생길때 전역변수에서 가져오는것이 아닌,
rest api로 값들을 매번 가져오는것

즉 채팅메시지 function send() 를 보낼때마다 계속해서 가져오게됨

**Comment by ytw9699** [comment]
@jongfeel 두번째 방법으로 변경을 하려하는데 그랬을 경우, 채팅메시지를 1회 보낼때마다 추가적인 요청이 1~2번 더 들어가게 됩니다. 그것을 감수하고서라도 조금 더 안전함을 택하려하는데 어떻게 생각하실지요

**Comment by ytw9699** [comment]
@jongfeel 
https://github.com/ytw9699/Dokky/pull/239#discussion_r499320482
여기서 말씀하신 전역변수의 경우 잠재적인 문제가 발생할수 있다고 하셨는데, 
결국 isLimited 변수값을 rest api로 필요할때마다 디비로부터 다시 가져오는것을 말씀하신거겠지요?

**Comment by jongfeel** [comment]
첫번째 코멘트에 대한 의견

안정성을 위해 그럴만한 가치가 있다고 판단이 되면 그렇게 하는게 맞습니다.

두번째 코멘트에 대한 의견

제가 얘기했던 건 isLimited는 변수 값이고 이게 전역변수이기 때문에 관리가 어렵다고 한겁니다.
객체지향적이지 않은 방식의 변수의 상태값 관리는 변수의 값이 언제 어떻게 변하는지에 대한 추적이 불가능하므로 문제가 발생할 수 있다고 한 것이었습니다.

즉, 변수의 값이 변화가 된 상태는 알 수 있는데, 그 값이 언제 누구에 의해서 변경되는지는 변수 값만으로는 알기 어렵다는 뜻입니다.

서버와 네트워크 연결을 통해 데이터를 가져오고 다시 업데이트가 되는 문제는 다른 문제이긴 합니다.

**Comment by ytw9699** [comment]
일단 chat_type 변수는 전역변수에서 완전히 삭제

필요할때마다 rest api로 가져오거나 

업데이트가 불필요한 경우는 처음에 페이지 요청시 넘겨온 값을 곧바로 사용

**Comment by ytw9699** [comment]
chatMembersArray값을 필요로 하는 곳이 생길때 전역변수에서 가져오는것이 아닌
rest api로 값들을 매번 가져오는것으로 모든 곳에서 변경

chatMembersArray전역변수는 완전히 삭제

https://github.com/ytw9699/Dokky/commit/4ced32eae2e156b9bdc427a54a17e949956a0acf
