### ISSUE TITLE
SPRING_SECURITY_SAVED_REQUEST control

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#55]
여러 가지로 찾아 봤지만 딱히 태원님 처럼 쓰고 싶어하는 사람이나 그런 방법이 있는 것 같지는 않아 보입니다.
#52 참고

사실은 지난 주에 찾아보고 적어 두려고 했는데 잠깐 잊고 있었네요.
혹시 찾으신거 있으면 더 공유해 주셔도 될 것 같습니다.

**Comment by jongfeel** [comment]
회사에 SpringFramework 잘 아는 분한테 얘기해 봤는데

SPRING_SECURITY_SAVED_REQUEST

이걸 직접 써서 하지는 않는다고 하더군요.

아무래도 사람들이 뭔가 security에서 제공해 주는 이 방식이 원하는대로 동작 안해서 안쓰는(?) 느낌도 듭니다.

그래서 어떻게 하냐고 물어보니까
아예 user role을 줘서 해당 url (controller의 method) 요청시 권한이 없으면 그냥 페이지 자체를 막아 버린다고 하더라고요. 쓰는 사람은 불편한 방식인데, 만드는 사람이 편한 방식이죠.
그리고 REST API 위주의 작업만 해 오셔서, security 쪽은 기본적인 것만 쓴다고 합니다.

**Comment by ytw9699** [comment]
우와~~~~~멘토님ㅠㅠㅠ

이렇게까지 신경쓰고 알아봐주셔서 너무 감사합니다!ㅎㅎ

사용자보다는 개발자에게 편한 방식으로 하셨나보네요~

그리고 평소 생각했던 스프링 시큐리티가 의외로 빈약한걸수도 있을것같네요

어찌됬든 다음 리뷰시간까지만 알아보고 SPRING_SECURITY_SAVED_REQUEST는 마무리 지어야겠습니다^^

정말 감사합니다.
