### ISSUE TITLE
Tomcat problem

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#59]
참조 wiki
https://github.com/ytw9699/Dokky/wiki/02.19~03.03.-%EB%A6%AC%EB%B7%B0

## Tomcat 실행이 안된 이유 찾기

- server.xml에서 Host context가 주석처리가 안되어 있는 상태로 실행되서 안됨
- 주석 처리 후 정상 작동

**Comment by ytw9699** [comment]
톰캣이 돌지않는 현상+ 8080포트가 열리지않는 현상의 문제해결

1차 적으로
프로젝트를 undeploy한상태에서 만약 톰캣을 restart 했다면
<"Context docBase="dokky" path="/" reloadable="true" />부분의 주석처리가 필요
톰캣을 restart하지않았다면 undepoly했어도 윗부분 주석처리없이 depoly가능
