### ISSUE TITLE
[보류] Deployment의 개선 필요성

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#60]
## 관련 링크
https://github.com/ytw9699/Dokky/wiki/02.19~03.03.-%EB%A6%AC%EB%B7%B0

## delivery의 문제 인식

- 프로젝트 빌드 후 dokky.war 파일 외에
- tomcat 환경 세팅도 자동 배포 스크립트가 필요
- 어쩌면 서버 환경까지 한꺼번에 배포가 가능한 방법이 있을 수 있음
- AWS CodeDeploy

**Comment by ytw9699** [comment]
톰캣이 돌지않는 현상+ 8080포트가 열리지않는 현상의 문제해결

1차 적으로
프로젝트를 undeploy한상태에서 만약 톰캣을 restart 했다면
<"Context docBase="dokky" path="/" reloadable="true" />부분의 주석처리가 필요
톰캣을 restart하지않았다면 undepoly했어도 윗부분 주석처리없이 depoly가능

2차적으로
프로젝트를 배포하듯 톰캣 sever.xml도 배포가 가능하고
여기서 더 나아가 도커를 활용할수 있음

**Comment by ytw9699** [comment]
톰캣의 server.xml의 설정 자체를 건드리지 않는 방법을 쓰자
 	
 	 	먼저 기본적으로 톰캣에 /경로로 배포된,내장된 ROOT를 undepoly해준다(/var/lib/tomcat9/webapps/ROOT 를 비워줌)
 	
 	 	server.xml의 Context docBase 설정은 주석처리를 그대로 해두고 앞으로도 건들지 말자
 	
 	 	pom.xml에서 <path>/</path>로 지정해준다 그러면 배포 되는 경로는
 	
 	 	/var/lib/tomcat9/webapps/ROOT 로 배포가 되버린다. ROOT.war도 생성
 	
 	 	그 후에 dokky.ga로 접속시 바로 메인으로 접속된다. 
 	
 	 	왜 이렇게 접속이 되냐면 톰캣의 기본 Document Root는 webapps/ROOT로 되어있다고 한다.
 	 	
 	 	http://내아이피:8080으로 접속시  기본적인 루트는 ROOT 디렉토리 밑이 된다는것이다.
 	 
 	 	제일 간단한 방법인데 단점 및 문제점이라고 아직까진 없는것 같다.

**Comment by jongfeel** [comment]
> 톰캣의 server.xml의 설정 자체를 건드리지 않는 방법을 쓰자
> 
> ```
>  	먼저 기본적으로 톰캣에 /경로로 배포된,내장된 ROOT를 undepoly해준다(/var/lib/tomcat9/webapps/ROOT 를 비워줌)
> 
>  	server.xml의 Context docBase 설정은 주석처리를 그대로 해두고 앞으로도 건들지 말자
> 
>  	pom.xml에서 <path>/</path>로 지정해준다 그러면 배포 되는 경로는
> 
>  	/var/lib/tomcat9/webapps/ROOT 로 배포가 되버린다. ROOT.war도 생성
> 
>  	그 후에 dokky.ga로 접속시 바로 메인으로 접속된다. 
> 
>  	왜 이렇게 접속이 되냐면 톰캣의 기본 Document Root는 webapps/ROOT로 되어있다고 한다.
>  	
>  	http://내아이피:8080으로 접속시  기본적인 루트는 ROOT 디렉토리 밑이 된다는것이다.
>  
>  	제일 간단한 방법인데 단점 및 문제점이라고 아직까진 없는것 같다.
> ```

이건 root 경로에 그냥 배포하는 방법을 적으신 것 같고,
여러 서버 + 여러 경로의 조합으로 배포하려면 항상 pom.xml을 수정해야 하니까
command line script 같은 걸 만들어 보면 어떨까 싶네요.
