### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#61]
관련 링크
https://github.com/ytw9699/Dokky/wiki/02.19~03.03.-%EB%A6%AC%EB%B7%B0

배포할 때 생기는 에러 메시지
`FAIL - Deployed application at context path / but context failed to start`

???

관련 자료를 더 찾아보고 시도해 봐야 할 듯 하네요.

**Comment by jongfeel** [comment]
@ytw9699 
어떻게 Done 상태가 됐는지 내용 추가해 주세요.

**Comment by ytw9699** [comment]
해결방법 입니다.

 	- spring-web jar파일 중 예전 버전을 dokky서버에서 배포 할때마다 반복적으로 삭제해준다(임시방법)
 	(rm spring-web-5.0.15.RELEASE.jar)
 	
 	- 애초에 배포 할때 한 버전만 배포되도록 한다(완전 해결 방법)
 	 	
 	- 데스크탑의 Dokky\dokky\target 폴더를 지우고 다시 배포한다
 	(폴더를 지울경우 다시 deploy를 할때 하나의 jar파일만 생성해서 target 폴더에 보관후 배포를 해준다)
 	
 	- 또는 이클립스 run as > maven clean 버튼을 통해 dokky서버를 clean 해준다. 톰캣을 clean하는게 아니다.
 	(그러면 target 폴더와 연관된 파일 및 기타적인것들을 삭제시켜준다.
 	그리고 위처럼  다시 deploy를 할때 하나의 jar파일만 생성해서 target 폴더에 보관후 배포해준다)

**Comment by ytw9699** [comment]
문제 원인과 느낀점 대비책등을 위키에 정리해뒀습니다.
https://github.com/ytw9699/Dokky/wiki/03.04~03.10.-%EB%A6%AC%EB%B7%B0

**Comment by jongfeel** [comment]
# 문제 해결 과정
- 구글링을 하다가 maven clean에 대한 단서를 찾고 실행
- 이클립스에 maven clean과 target 폴더에 배포되는 jar 파일들의 상태가 다르다는 걸 알게 됨
- `spring-web-`으로 시작하는 jar 파일이 2개의 버전이 있으면 문제 생김

**Comment by ytw9699** [comment]
데스크탑의 repository 폴더 :   C:\Users\champ\.m2\repository

이 주소의 폴더는 현재 데스크탑의 이클립스에서 참조하고있는 디펜던시들이 모두 모여있는곳이다

우분투로 배포되는 lib 폴더 : F:\java\GitApp\Dokky\dokky\target\dokky-1.0.0-BUILD-SNAPSHOT\WEB-INF\lib

이 주소의 폴더는 도키프로젝트가 우분투로 배포될때 참조하는 디펜던시들이 모여있는 곳이다

평소 데스크탑의 repository 폴더의 존재만 알고있었고 이 폴더로부터 디펜던시들이 우분투로 배포가 된다고 생각하고있었다. 

하지만 실제로 배포를 담당하는 폴더는 따로 있었고 이를 알지 못했다.
이곳의 jar파일들은 버전이 다르게되면 중복되서 쌓이게 되는 특징이 있다. 
이를 해결하려면 이클립스에서 mvn clean 을하거나 lib폴더를 직접 비워야 한다.

특히 다른 디펜던시들은 중복이되도 아무런 문제가없는데, spring-web이라고 하는 디펜던시는

버전이 중복되어 배포되면 문제가 생긴다는것이다.

**Comment by ytw9699** [comment]
일반적인 자바 프로젝트의 경우 src폴더에 .java확장자 파일들이 bin폴더에 .class파일들이 저장되는데
메이븐 프로젝트의 경우 이 target이라는 폴더가 컴파일한 .class파일들을 저장하는 특성을 가진다는것 이러한 전체적 구조에 대해알아야한다.

**Comment by ytw9699** [comment]
![image](https://user-images.githubusercontent.com/35983608/76852402-930d7980-688e-11ea-91be-7000d16734e6.png)

이제야 build path라는게 뭔지 이해를 했는데..
말 그대로 build를 하는 path 경로라는 뜻인데
위 그림에서 보듯이 source탭은 .java파일이 저장되는 위치를 지정한것이고
.classs파일들은 dokky/target/classes로 되어있다. 이를 사용자가 자신의 환경에 맞게
변경도 가능하다.
