### ISSUE TITLE
OAuth2.0 관련 리뷰 요청

### ISSUE THREAD

**Issue by jongfeel** [ytw9699/Dokky#83]
예전 기억도 떠올려 볼겸 해서 OAuth2.0 리뷰를 했으면 하는데요
https://github.com/ytw9699/Dokky/blob/master/dokky/meetings/20191217%2312_%EC%8A%A4%EC%8A%A4%EB%A1%9C%EC%9D%98%EC%84%B1%EC%9E%A5_oauth%2C%20process%2C%20servlet.md

사실 저도 정확히 모르고 알려드린 것도 있던 것 같아서요.
최근에 OAuth2.0 client 측만 개발 하다 보니 서버 쪽 세팅을 어떻게 해야 auth server, resource server를 통한 code, token, refresh token이 가능한지 더 정확하게 알게 됐다고나 할까요?

한 20분 정도 예전에 태원님이 정리하신 블로그 보고 정리해 보면 될 거 같아요.

**Comment by ytw9699** [comment]
네 멘토님, 리뷰를 다시 했으면 하는 범위가, 제가 예전에 정리해두었던 OAuth2.0 관련 전체적인 동작 모든 이론(블로그)  다시 정리후에 그 내용들을 멘토님과 한번 더 얘기를 해보시자는 말씀이신가요~?

**Comment by jongfeel** [comment]
아닙니다.

따로 정리 안하셔도 되고요.

현재 상태에서 리뷰를 해 보고 잘못 알고 있던게 발견되면 코멘트를 다는 식으로 진행하려고요.

**Comment by ytw9699** [comment]
네 일단 블로그 auth내용 정리해둔곳입니다.

https://cg-developer.tistory.com/361

다시 기억해보면, 어떻게 전체적으로 돌아간다는 뼈대 정도?에서 이해 했던것 같아요. 

워낙 생소하기도하고, 깊이 이해하기에는 어려웠던것 같네요.

**Comment by jongfeel** [comment]
링크 달아주셔서 감사합니다.

미팅 시간에 리뷰 함께 했으면 합니다.

**Comment by ytw9699** [comment]
네 알겠습니다 감사합니다~

**Comment by jongfeel** [comment]
#88 OAuth2.0 리뷰 진행
