### ISSUE TITLE
[보류] 우분투에서 톰캣9.0로그를 완전히 찍지 못하는 현상

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#85]
컨트롤러, 서비스클래스등 에서 log4j등을 통해 로그를 찍어둔것을 

우분투환경에서 확인 못하는 현상..

![image](https://user-images.githubusercontent.com/35983608/76677042-c2ad4f00-660c-11ea-94af-1e2cefebce7c.png)

해볼수있는것들은 아래 파일들을 살펴보는것인데

localhost.2020-03-14.log 
catalina.2020-03-14.log
localhost_access_log.2020-03-14.txt

tail -f , tail -n500 등의 명령어로 열어보아도 

컨트롤러,서비스 클래스등에서의 로그는 전혀 보이지가 않는다.

로그가 계속해서 보이지 않으니 문제해결에 어려움을 겪는다..

**Comment by ytw9699** [comment]
문제해결의 실마리를 찾을수도있을듯한 구글링
https://serverfault.com/questions/993398/tomcat-9-catalina-out-log-file-missing-and-console-printouts-are-not-shown-any

**Comment by ytw9699** [comment]
또다른 구글링 결과 생략된 로그를 보고싶으면
systemctl status tomcat9.service 명령어에 -l를 사용하라고 하는데 소용이없다.
(use -l to show in full log service)

로그 설정을 찾아가 logging.properties열어보면
/etc/tomcat9/logging.properties
/usr/share/tomcat9/etc/logging.properties

디렉토리 위치도 ${catalina.base}/logs로 되어있고..
logs의 존재는 /var/lib/tomcat9/logs 여기밖에없다는것..

1catalina.org.apache.juli.AsyncFileHandler.level = FINE
1catalina.org.apache.juli.AsyncFileHandler.directory = ${catalina.base}/logs
1catalina.org.apache.juli.AsyncFileHandler.prefix = catalina.
1catalina.org.apache.juli.AsyncFileHandler.maxDays = 90

2localhost.org.apache.juli.AsyncFileHandler.level = FINE
2localhost.org.apache.juli.AsyncFileHandler.directory = ${catalina.base}/logs
2localhost.org.apache.juli.AsyncFileHandler.prefix = localhost.
2localhost.org.apache.juli.AsyncFileHandler.maxDays = 90

로그 레벨도 INFO로 데스크탑의 레벨과 같다

org.apache.catalina.core.ContainerBase.[Catalina].[localhost].level = INFO
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].handlers = 2localhost.org.apache.juli.AsyncFileHandler

보통적으로 생각하면 catalina.2020-03-14.log 이파일을 열었을때 분명 로그가 찍혀야 되는건데..
안찍히니 톰캣 9.0에 설정이 뭔가 막혀있는듯한 느낌을 받는다..

**Comment by ytw9699** [comment]
journalctl -u tomcat9.service 라는 명령어를 통해 확인후 G라고 입력해주고
몇만줄이나 되기때문에 몇초 기다리면 가장 밑의 페이지의 로그를 보여준다.

**Comment by jongfeel** [comment]
https://sarc.io/index.php/tomcat/900-apache-tomcat-java-logging-juli

여기 2-2의 내용을 보면 catalina.YYYY-MM-DD.log 찍은 로그의 경우 standard in/out을 찍지 않는다고 하네요.

2-4의 로그 관리 전략을 참고해 보는 건 어떨까요?

**Comment by jongfeel** [comment]
https://serverfault.com/questions/966281/ubuntu-18-04-2-build-of-tomcat-9-not-writing-to-catalina-out-but-in-systemd-sta

문제상황
tomcat9에서 catalina.out 파일은 어디에 생성되는가???

문제를 해결할 수 있는 방법 research.

**Comment by ytw9699** [comment]
현재 우분투에 설치된 톰캣9의

카탈리나 base는

Using CATALINA_BASE:   /usr/share/tomcat9

![image](https://user-images.githubusercontent.com/35983608/78243092-14673c00-751e-11ea-94b6-eba334da3b49.png)
