### ISSUE TITLE
dokky서버에서 today수를 가져오지 못하는 현상

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#86]
데스크탑에서는 아무문제없이 오늘의 total수를 가져오는데
dokky서버에서는 가져오지를 못한다

이것 또한 시간차이의 문제와 겹치는 문제라고 강하게 의심이 된다.

sysdate, utc, kst, timezone 과 관련해 분명 문제가 있다..

데스크탑의 환경에서는 문제가없는데 우분투환경에서는 문제가 있다면

분명 환경의 설정차이인것인데 그부분을 찾아야한다.

<select id="getVisitTodayCount" resultType="int">
	select count(*) from dk_visitor where substr(to_char(visit_time), 1, 9) = to_char(sysdate, 'yy/MM/dd')
</select>

**Comment by jongfeel** [comment]
#84 요 이슈와 연관이 있어 보이네요

**Comment by ytw9699** [comment]
넵 맞아요 2가지가 같은 문제인걸로 생각됩니다ㅎㅎ

**Comment by ytw9699** [comment]
우분투와 데스크탑에서 같은 DOKKY DB로 접속해 쿼리를 실행하고
로그를 정확히 찍어보았다.
차이가 난다

1. 가장 최근의 방문자의 시간 : 두 서버모두 같은 결과를 가져온다

select visit_time from dk_visitor where visitor_num = 14667

![image](https://user-images.githubusercontent.com/35983608/76925472-ef1edf00-691c-11ea-8765-bdfe7693f8dc.png)

2. 현재 날짜가져오기 : 두 서버 모두 같은 결과
select to_char(sysdate, 'yy/MM/dd') from dual
![image](https://user-images.githubusercontent.com/35983608/76929770-5726f280-6928-11ea-86ed-da48588e9994.png)


3. 가장 최근의 방문자의 시간을 짜르게된 결과 :  두 서버의 결과가 다르다
select substr(to_date(visit_time), 1, 9) from dk_visitor where visitor_num = 14667

데스크탑  : 
![image](https://user-images.githubusercontent.com/35983608/76929656-17f8a180-6928-11ea-851d-f33c83abf7e2.png)

도키 :
![image](https://user-images.githubusercontent.com/35983608/76929670-1f1faf80-6928-11ea-9afa-2ae34eddc616.png)

결과가 달라지는 이유는..?같은 명령어인데..?
같은 도키 DB로부터 가져오는것인데
다른것이라곤 운영체제가 다를뿐이다
윈도우와 , 우분투
그래서 우분투쪽에서도 
 ec2타임존 kst로 변경을 하였음에도 왜 소용이없는것인지..
ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

**Comment by ytw9699** [comment]
우분투의 타임존 설정을  Asia/Seoul로 정확히 바꿧음에도 불구하고 
select substr(visit_time, 1, 9) from dk_visitor where visitor_num = 14667
결과가 18-MAR-20  계속 똑같다 
쿼리에서 substr을 할때 이것 또한 운영체제의 영향을 받는것으로 파악된다..
왜 substr이라는 함수에서 굳이 운영체제에 따라 값이 달라지는건지는 모르겠지만..

**Comment by jongfeel** [comment]
string은 언어 즉 locale에 따라 표현 방식이 달라집니다.
그래서 substr 방식 말고 써 놓은 것 중에

``` SQL
select to_char(sysdate, 'yy/MM/dd') from dual
```

이렇게 통일하는게 좋을 것 같네요.
그러면 어떤 운영체제 어떤 언어 어떤 국가 표현 방식을 쓰더라도 같게 나올겁니다.

**Comment by ytw9699** [comment]
네 계속 테스트하다가 발견했는데 이렇게 쿼리를 뽑아보니까 잘 되더라구요
중간에 'yy/MM/dd' 이부분을 추가해줬어요 그러니 잘 되더라구요

select count(*) from dk_visitor where substr(to_char(visit_time,'yy/MM/dd'), 1, 9) = to_char(sysdate, 'yy/MM/dd')

그래서 이건 timezone설정과 연관이 있을거라고 처음 생각했던거랑은 무관했던것 같아요

그리고 멘토님 말씀대로 String은 계속 표현방식이 달라지니 이렇게 통일하는 방법 밖에는 없는것 같네요~!
