### ISSUE TITLE
아이디에서 닉네임으로 표시 바꾸기

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#89]
소셜에서 가져온 숫자형식의 아이디(오픈?아이디)로 변경되었기 때문에

도키의 모든 곳(게시글보기, 댓글보기, 결제관리등)에서 아이디표시를 없애고 닉네임으로 변경하기

관련된 쿼리, 테이블까지 모두 변경 필요.

**Comment by jongfeel** [comment]
진행 상황이 어떻게 됐는지 알려주시면 좋겠습니다.
