### ISSUE TITLE
사이트내에서 급한 디자인 및 화면단 작업들 처리

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#90]
사이트내에서 급한 디자인 작업들 처리

**Comment by jongfeel** [comment]
어떤 디자인 작업들인지 목록을 적을 수 있을까요?

**Comment by ytw9699** [comment]
네 목록입니다.

1. 모든 닉네임 글자수에 따른 디자인 작업
2. 로그인 페이지 디자인 및 로그인버튼 사진 수정 작업
3. 메인페이지 하단 내용 및 디자인 작업
4. 경고창 바꾸고 도키에 맞는 디자인 작업
5. 리스트 및 상세보기 디자인 뒤틀림 바로잡는 작업

**Comment by jongfeel** [comment]
요렇게 목록으로 만들고 체크하는 방법으로 해도 됩니다.
체크박스는 edit 모드가 아니어도 동작하고
github가 목록의 진행상황까지 표시해줘서 좋은 기능이니 써보세요.

- [ ] 모든 닉네임 글자수에 따른 디자인 작업
- [ ] 로그인 페이지 디자인 및 로그인버튼 사진 수정 작업
- [ ] 메인페이지 하단 내용 및 디자인 작업
- [ ]  경고창 바꾸고 도키에 맞는 디자인 작업
- [ ] 리스트 및 상세보기 디자인 뒤틀림 바로잡는 작업

**Comment by ytw9699** [comment]
우와 이런것도 있을줄이야 완전 신기하네요 멘토님 감사합니다!
