### ISSUE TITLE
tomcat context 의 재설정 및 80포트로 정적파일 인식 못함 현상, 서버의 자원사용 최소화

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#92]
1. 완성하고자 하는것 및 현재 해결 되지 않은 문제점

- 서버의 자원을 낭비 하지 않기 위해 dokky 프로젝트를 단 하나만 돌리는것(여러 프로젝트가 배포되면 안됨)
-  80 포트로 접속시에도 경로 설정을 제대로 잡아, 정적파일은 바로 인식하는것
-  dokky.ga 로 접속시 바로 메인페이지가 나와야 하는것
- 즉 dokky.ga/dokky 가 아닌 dokky.ga 로 접속이 되야하는것
- 현재 아파치의 웹루트의 경로와 톰캣의 웹루트의 경로가 다르다 이것을 일치시켜줘야한다.
그래야 80으로 접속하던, 8080으로 접속하던 정적파일을 모두 읽어들일 수 있다.

**Comment by ytw9699** [comment]
현재까지 정적파일은 아파치가 처리하는줄 알고 있었으나, 443포트로 들어오는 요청의 확인결과 톰캣이 모든걸 처리하고 있었다. 처음에 의도했던게 아파치와 톰캣의 역할을 잘 배분해보자 라는것이였는데, 알고보니 제대로 안되어있었고, 다시 새로운 서버로의 이전으로 인해 발견 할수 있었음.

**Comment by ytw9699** [comment]
경로 설정 해결완료

1. 아파치 80서버의 설정
sudo nano /etc/apache2/sites-available/000-default.conf 파일에서는

RedirectPermanent / https://dokky.ga 로 디라이렉트 설정을 걸어두었고

2. SSL 443 설정
sudo nano /etc/apache2/sites-available/default-ssl.conf 에서는

DocumentRoot /var/lib/tomcat9/webapps/ROOT/

 JkMount /* tomcat1     //동적 컨텐츠 톰캣처리
 SetEnvIf Request_URI "/*.css" no-jk     //정적 컨텐츠 아파치 처리
 SetEnvIf Request_URI "/*.jpg" no-jk
 SetEnvIf Request_URI "/*.gif" no-jk
 SetEnvIf Request_URI "/*.png" no-jk
 SetEnvIf Request_URI "/*.html" no-jk
 SetEnvIf Request_URI "/*.js" no-jk

3. 처음에
DocumentRoot /var/lib/tomcat9/webapps/ROOT/ 라고 설정을 해두고 테스트를 해보았으나
되지 않았다. 하지만 다시 시도해보니 정삭적으로 경로가 잡힘

아마도 "/" 빼먹었거나, 서버 재시작이 제대로 안됬거나 하지 않았을까 싶다..

혹시 나 또 다른 설정이 있나 싶어 애꿎은 곳에서만 찾고있었다..
sudo nano /etc/apache2/apache2.conf

**Comment by ytw9699** [comment]
/var/lib/tomcat9/webapps# sudo chmod 755 -R ROOT 로 폴더의 권한을 열어줌으로써 막혀있던 접근이 열리게됨

**Comment by jongfeel** [comment]
새로운 배포 환경에서의 경로 변경에 대한 수정 작업이 필요하다는 내용도 적어주세요.

**Comment by ytw9699** [comment]
배포 경로의 변경

기존 : /var/lib/tomcat9/webapps/dokky 

현재 : /var/lib/tomcat9/webapps/ROOT

위와 같이 변경이 되었기에

기존 : DocumentRoot /var/lib/tomcat9/webapps/

현재 : DocumentRoot /var/lib/tomcat9/webapps/ROOT/ 

로 변경 필요

**Comment by ytw9699** [comment]
멘토님 리뷰 내용 :
생각한 대로 동작하는지에 대한 검증
아파치와 톰캣이 동시에 동작하고 있다고 생각하고 처리를 했지만, 실제는 톰캣만 동작하고 있던 상황이었을때
보통 사람: 아파치를 다시 정상적으로 돌리고 둘이 연동하게끔 수정함
더 중요한 포인트: 자신의 생각과 행동의 불일치성을 줄이기 위한 검증 작업이 필요

여기서 검증작업이 필요하다는게 굉장히 중요한 포인트!
